import { ArrowLeft, Check, FileText, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { Container } from "@/components/ui/container";

const policies = {
  "shipping-policy": { title:"Shipping policy", eyebrow:"Policy / Delivery", updated:"Effective 01 Aug 2026", intro:"How serviceability, fulfilment, courier handoff, estimates, NDR, and delivery evidence work.", sections:[["Serviceability and estimates","Delivery availability and estimates are recalculated for the verified address and current bag. Estimates are not a guarantee until the order is confirmed."],["Dispatch and tracking","A privacy-safe tracking token shows the normalized courier timeline without exposing the customer name, full address, mobile number, or payment data."],["Delivery exceptions","NDR, address correction, reattempt, and return-to-origin actions follow the courier and order state. Support can explain the available next actions."]] },
  "return-policy": { title:"Return policy", eyebrow:"Policy / Returns", updated:"Effective 01 Aug 2026", intro:"Eligibility, evidence, pickup, quality control, exchange reservations, and refund outcomes in plain language.", sections:[["Eligibility","Eligible pieces can be requested within the displayed return window. Final-sale, worn, washed, or damaged items may be excluded according to the product and order snapshot."],["Evidence and quality control","Some reasons require photos. Returned items are scanned and inspected before the stock and money outcome becomes final."],["Refund timing","Approved refunds return to the stated destination after provider completion. The account timeline shows canonical progress and masked references."]] },
  privacy: { title:"Privacy notice", eyebrow:"Policy / Privacy", updated:"Effective 01 Jul 2026", intro:"What the storefront displays, why account context is protected, and how operational access remains scoped and audited.", sections:[["Customer data","Public pages do not expose owned order, address, payment, return, review, or support records. Tracking uses an unguessable token and a minimal projection."],["Staff access","Operations roles receive explicit permissions and resource scopes. Customer fields are masked by default; narrower access requires a reason and audit event."],["Frontend preview","This current frontend uses local fixtures. It does not send credentials, payments, support messages, or business mutations to a backend."]] },
  terms: { title:"Terms of use", eyebrow:"Policy / Terms", updated:"Effective 01 Aug 2026", intro:"The storefront preview, product information, account responsibilities, and future API-authoritative commerce contract.", sections:[["Product and price","Availability, price, promotion, delivery, tax, and final order state are revalidated before a production order is accepted."],["Account responsibility","Keep credentials private and review active sessions. Customer and staff accounts are separate audiences and cannot be used interchangeably."],["Preview limitation","Buttons labelled preview prepare only local UI state. No purchase, return, refund, campaign, or operational action is executed without the future API."]] },
};

export type PolicySlug = keyof typeof policies;
export const policySlugs = Object.keys(policies) as PolicySlug[];

export function PolicyPage({ slug }: { slug: string }) {
  const policy = policies[slug as PolicySlug] ?? policies.privacy;
  return <div className="policy-page"><Container><Link href="/" className="policy-back"><ArrowLeft size={15} /> Storefront</Link><header><FileText size={25} /><p className="eyebrow">{policy.eyebrow}</p><h1>{policy.title}.</h1><p>{policy.intro}</p><span>{policy.updated} · en-IN</span></header><div className="policy-layout"><aside><strong>On this page</strong>{policy.sections.map(([title],index) => <Link href={`#policy-${index + 1}`} key={title}>0{index + 1} / {title}</Link>)}<div><ShieldCheck size={18} /><p>Published policy content is versioned and validated before release.</p></div></aside><article>{policy.sections.map(([title,copy],index) => <section id={`policy-${index + 1}`} key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{copy}</p></section>)}<footer><Check size={17} /><p><strong>Need account-specific help?</strong><span>Sign in before sharing an order, payment, shipment, or return reference.</span></p><Link href="/contact">Contact support</Link></footer></article></div></Container></div>;
}
