<?php

declare(strict_types=1);

/**
 * Front controller.
 *
 * GENERATED by tools/live/build-live.mjs — edit tools/live/templates/api-index.php.
 *
 * The named endpoint files beside this one are the readable map of the API.
 * This file is the dispatcher the web server falls back to for any path an
 * endpoint file cannot be reached at directly — chiefly parameterised paths
 * such as /api/v1/orders/ord-local-07. Both lead to the same route table and
 * the same middleware pipeline.
 *
 * The only difference from the repository's api/index.php is where the root
 * comes from: there it is the folder above; here it is outside the document
 * root, so _backend.php names it.
 */

use Iced\Kernel\Application;

header_remove('X-Powered-By');

/** @var string $root */
$root = require __DIR__ . '/_backend.php';

require $root . '/autoload.php';

Application::boot($root)->run();
