<?php

declare(strict_types=1);

/**
 * Shared boot for every file under api/v1/. Each endpoint file requires this,
 * then calls Endpoint::serve() with the name(s) of the route it answers.
 *
 * GENERATED by tools/live/build-live.mjs — edit
 * tools/live/templates/api-bootstrap.php.
 */

// expose_php=Off is the deployment setting; this covers hosts that leak it.
header_remove('X-Powered-By');

/** @var string $root */
$root = require __DIR__ . '/_backend.php';

require $root . '/autoload.php';

class_exists(Iced\Kernel\Endpoint::class);
