<?php

declare(strict_types=1);

/**
 * Finds the backend's root — the folder holding autoload.php, config/ and src/ —
 * and returns its absolute path.
 *
 * GENERATED by tools/live/build-live.mjs — edit tools/live/templates/api-backend.php.
 *
 * Only two files require this one: index.php and bootstrap.php. Everything below
 * them works the path out for itself (Kernel\Endpoint derives it from where src/
 * is), so this is the single place the deployment layout is stated.
 *
 * It walks UP from here and accepts the first of two shapes it meets, which
 * covers every layout the build produces without anything to configure:
 *
 *   FLAT — the backend is the document root itself, beside the site's files:
 *
 *       <document root>/
 *       ├── index.html  _next/  men.html  …   the storefront
 *       ├── autoload.php  config/  src/  …    the backend  ← found here
 *       ├── .env
 *       └── api/v1/_backend.php               ← you are here
 *
 *   SPLIT — the backend is a folder called `iced-out-api`, above the document
 *   root, where no URL can reach it at all:
 *
 *       /home/USER/iced-out-api/              ← found here
 *       /home/USER/public_html/iced-out/
 *                  └── api/v1/_backend.php    ← you are here
 *
 * If neither is where the search can see it, set $explicit below.
 */

/* ── The one line to edit if the search below cannot find the backend. ─────
   Example: $explicit = '/home/myuser/iced-out-api'; */
$explicit = '';

/** Both marker files, because autoload.php alone is not proof of much. */
$isBackendRoot = static fn (string $directory): bool =>
    is_file($directory . '/autoload.php') && is_file($directory . '/config/app.php');

$fail = static function (string $message): never {
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(
        ['error' => ['code' => 'ICE-SYS-500', 'message' => $message, 'retryable' => false]],
        JSON_UNESCAPED_SLASHES,
    );

    exit;
};

if ($explicit !== '') {
    if (!$isBackendRoot($explicit)) {
        $fail('The path set in api/v1/_backend.php has no autoload.php and config/app.php in it.');
    }

    return $explicit;
}

$directory = __DIR__;

for ($step = 0; $step < 8; ++$step) {
    $parent = dirname($directory);

    if ($parent === $directory) {
        break;
    }

    $directory = $parent;

    /* SPLIT first: if a folder of that name is here, it is unambiguously the
       backend. Checking it before the flat shape means a split deployment can
       never accidentally match some other directory on the way up. */
    if ($isBackendRoot($directory . '/iced-out-api')) {
        return $directory . '/iced-out-api';
    }

    if ($isBackendRoot($directory)) {
        return $directory;
    }
}

$fail(
    'The backend was not found. Expected autoload.php and config/ either beside the site files '
    . 'in the document root, or in an iced-out-api folder above it. Upload them, or set $explicit '
    . 'in api/v1/_backend.php.',
);
