<?php

declare(strict_types=1);

/**
 * Reads out why the server is failing, and then asks to be deleted.
 *
 * GENERATED by tools/live/build-live.mjs — edit tools/live/templates/diagnose.php.
 *
 * APP_DEBUG=false keeps stack traces out of API responses, which is correct and
 * also why a live 500 says nothing useful in a browser. The exception is in
 * storage/logs — and storage/ is denied to the web, correctly. This page is the
 * one sanctioned way to read it, plus the handful of environment facts that
 * explain most of what goes wrong on a shared host.
 *
 * Gated on SETUP_TOKEN in .env exactly like setup.php: blank ⇒ inert.
 */

use Iced\Kernel\Application;
use Iced\Kernel\Database;
use Iced\Support\Config;
use Iced\Support\Env;

/** @var string $root */
$root = require __DIR__ . '/api/v1/_backend.php';

require $root . '/autoload.php';

$app = Application::boot($root);
$container = $app->container;

$expected = Env::string('SETUP_TOKEN');
$supplied = is_string($_GET['token'] ?? null) ? $_GET['token'] : '';

$html = static fn (string $text): string => htmlspecialchars($text, ENT_QUOTES, 'UTF-8');

$fatal = null;
$sections = [];

if ($expected === '') {
    $fatal = 'SETUP_TOKEN is blank in .env, so this page is switched off. Set it to any long '
        . 'random string, reload, then blank it again and delete this file when you are done.';
} elseif (!hash_equals($expected, $supplied)) {
    $fatal = $supplied === ''
        ? 'Add ?token=... to the address. The token is SETUP_TOKEN in .env.'
        : 'That token does not match SETUP_TOKEN in .env.';
} else {
    /* ── 1. PHP itself ──────────────────────────────────────────────────── */
    $algos = password_algos();
    $hasArgon = in_array('argon2id', $algos, true);

    $php = [
        'version' => PHP_VERSION,
        'sapi' => PHP_SAPI,
        'password_algos()' => implode(', ', $algos) ?: '(none!)',
        'argon2id available' => $hasArgon ? 'yes' : 'NO  <-- see the note below',
    ];

    foreach (['pdo_mysql', 'mbstring', 'openssl', 'gd', 'json', 'fileinfo'] as $extension) {
        $php['ext ' . $extension] = extension_loaded($extension) ? 'loaded' : 'MISSING';
    }

    $sections['PHP'] = $php;

    /* A real hash + verify, because "the extension is loaded" and "the call
       works" are different claims and only the second one matters. */
    $hashCheck = [];

    try {
        $probe = password_hash('probe', $hasArgon ? PASSWORD_ARGON2ID : PASSWORD_BCRYPT);
        $hashCheck['password_hash'] = 'ok (' . substr((string) $probe, 0, 12) . '…)';
        $hashCheck['password_verify'] = password_verify('probe', (string) $probe) ? 'ok' : 'FAILED';
    } catch (Throwable $error) {
        $hashCheck['password_hash'] = 'THREW: ' . $error->getMessage();
    }

    $sections['Password hashing'] = $hashCheck;

    /* ── 2. Writable storage ────────────────────────────────────────────── */
    $storage = [];

    foreach (['storage', 'storage/logs', 'storage/cache', 'storage/media'] as $relative) {
        $path = $root . '/' . $relative;
        $storage[$relative] = !is_dir($path)
            ? 'MISSING'
            : (is_writable($path) ? 'writable' : 'NOT WRITABLE  <-- chmod 755, or 775');
    }

    $sections['Storage'] = $storage;

    /* ── 3. The database ────────────────────────────────────────────────── */
    /** @var Config $config */
    $config = $container->get(Config::class);
    /** @var Database $db */
    $db = $container->get(Database::class);

    $database = [
        'host' => $config->string('database.host') . ':' . $config->int('database.port', 3306),
        'name' => $config->string('database.name'),
        'user' => $config->string('database.user'),
    ];

    try {
        $db->pdo();
        $database['connection'] = 'ok (' . $db->flavour() . ')';

        foreach (['schema_migrations', 'users', 'products', 'store_settings', 'roles'] as $table) {
            try {
                $row = $db->selectOne(sprintf('SELECT COUNT(*) AS n FROM %s', $table));
                $database['rows in ' . $table] = (string) ($row['n'] ?? '?');
            } catch (Throwable $error) {
                $database['rows in ' . $table] = 'QUERY FAILED: ' . $error->getMessage();
            }
        }

        /**
         * Registering mints the customer's public id out of this settings row
         * (Support\IdAllocator — `id_pools` is a key in store_settings, not a
         * table of its own). Missing, registration fails and nothing else does,
         * which is the same shape of symptom as a broken hasher.
         */
        try {
            $setting = $db->selectOne('SELECT COUNT(*) AS n FROM store_settings WHERE `key` = ?', ['id_pools']);
            $database['store_settings.id_pools'] = ((int) ($setting['n'] ?? 0)) > 0
                ? 'present'
                : 'MISSING  <-- registration cannot mint a customer id';
        } catch (Throwable $error) {
            $database['store_settings.id_pools'] = 'CHECK FAILED: ' . $error->getMessage();
        }
    } catch (Throwable $error) {
        $database['connection'] = 'FAILED: ' . $error->getMessage();
    }

    $sections['Database'] = $database;

    /* ── 4. Deployment wiring ───────────────────────────────────────────── */
    $sections['Wiring'] = [
        'backend root' => $root,
        'APP_URL' => $config->string('app.url'),
        'APP_DEBUG' => $config->bool('app.debug') ? 'true' : 'false',
        'SESSION_SECRET' => $config->string('app.session.secret') === '' ? 'BLANK  <-- sessions cannot be signed' : 'set',
        'MAIL_DRIVER' => $config->string('app.mail.driver'),
    ];
}

/* ── 5. The actual exception, from the log ──────────────────────────────── */
$logLines = [];

if ($fatal === null) {
    $files = glob($root . '/storage/logs/app-*.log') ?: [];
    rsort($files);

    if ($files === []) {
        $logLines[] = 'No log files yet in storage/logs. If the directory is NOT WRITABLE above, '
            . 'that is itself the bug: nothing can be recorded, and every request that '
            . 'touches the rate limiter or a session fails.';
    } else {
        $recent = array_slice($files, 0, 2);

        foreach ($recent as $file) {
            $contents = (string) file_get_contents($file);
            $all = preg_split('/\R/', trim($contents)) ?: [];
            $tail = array_slice($all, -40);

            $logLines[] = '───── ' . basename($file) . ' (last ' . count($tail) . ' of ' . count($all) . ' lines)';
            $logLines = array_merge($logLines, $tail);
            $logLines[] = '';
        }
    }
}

http_response_code($fatal === null ? 200 : 403);
header('Content-Type: text/html; charset=utf-8');
header('X-Robots-Tag: noindex, nofollow');

?>
<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Iced_out - diagnose</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; padding: 2.5rem 1.25rem; background: #0b0b0c; color: #e8e8ea;
         font: 14px/1.65 ui-monospace, Menlo, Consolas, monospace; }
  main { max-width: 60rem; margin: 0 auto; }
  h1 { font-size: 1.3rem; margin: 0 0 .3rem; }
  h2 { font-size: .95rem; letter-spacing: .08em; text-transform: uppercase;
       color: #8b8b93; margin: 2rem 0 .6rem; }
  p.sub { color: #8b8b93; margin: 0 0 1rem; }
  pre { background: #141416; border: 1px solid #26262b; border-radius: 8px;
        padding: 1rem 1.15rem; overflow-x: auto; white-space: pre-wrap;
        word-break: break-word; margin: 0; }
  .bad { border-color: #7a2b2b; background: #1d1113; color: #ffb4b4; }
  .warn { border: 1px solid #7a5a1f; background: #1c1710; color: #ffd79a;
          border-radius: 8px; padding: 1rem 1.15rem; margin-top: 2rem; }
  table { border-collapse: collapse; width: 100%; }
  td { padding: .3rem .9rem .3rem 0; vertical-align: top; border-bottom: 1px solid #1c1c20; }
  td.k { color: #8b8b93; white-space: nowrap; width: 1%; }
  code { color: #9fd0ff; }
</style>
<main>
  <h1>Iced_out - diagnose</h1>
  <p class="sub">Delete this file when you are done.</p>

<?php if ($fatal !== null) { ?>
  <pre class="bad"><?= $html($fatal) ?></pre>
<?php } else { ?>

<?php foreach ($sections as $title => $rows) { ?>
  <h2><?= $html((string) $title) ?></h2>
  <table>
<?php foreach ($rows as $key => $value) { ?>
    <tr><td class="k"><?= $html((string) $key) ?></td><td><?= str_replace('&lt;--', '<span style="color:#ff9b9b">&lt;--', $html((string) $value)) ?></td></tr>
<?php } ?>
  </table>
<?php } ?>

  <h2>Last errors recorded</h2>
  <pre><?= $html(implode("\n", $logLines)) ?></pre>

  <div class="warn">
    <strong>Reading this:</strong> the line beginning <code>exception</code> in the log is the
    real cause of a 500 — everything before <code>#0</code> is the message.
    If <code>argon2id available</code> says <strong>NO</strong>, registration and login were
    fatal on this host until the build that made the hasher fall back to bcrypt; upload the
    current <code>src/</code> and try again.
    If any Storage row says <strong>NOT WRITABLE</strong>, fix that first — nothing can be
    logged or rate-limited without it.
    <br><br>
    <strong>Then delete <code>diagnose.php</code></strong> and blank <code>SETUP_TOKEN</code> in
    <code>.env</code>.
  </div>
<?php } ?>
</main>
