<?php

declare(strict_types=1);

/**
 * One-time installer — creates the schema and the starting data, then asks to
 * be deleted.
 *
 * GENERATED by tools/live/build-live.mjs — edit tools/live/templates/setup.php.
 *
 * On a server with SSH you would not need this: `php bin/console.php migrate`
 * and `php bin/console.php seed`, run inside iced-out-api/, do exactly the same
 * work. Shared hosting often has no shell, so this is the same two commands
 * behind a URL.
 *
 * It is gated on SETUP_TOKEN in the private .env. Blank ⇒ it refuses to do
 * anything at all, so an installer left behind by accident is inert rather than
 * a button anybody can press.
 */

use Iced\Kernel\Application;
use Iced\Kernel\Database;
use Iced\Support\Config;
use Iced\Support\Env;
use Iced\Support\Migrator;
use Iced\Support\Seeder;

/** @var string $root */
$root = require __DIR__ . '/api/v1/_backend.php';

require $root . '/autoload.php';

$app = Application::boot($root);
$container = $app->container;

$expected = Env::string('SETUP_TOKEN');
$supplied = is_string($_GET['token'] ?? null) ? $_GET['token'] : '';
$wantsDemo = ($_GET['demo'] ?? '') === '1';

$lines = [];
$note = static function (string $line) use (&$lines): void {
    $lines[] = $line;
};

$html = static fn (string $text): string => htmlspecialchars($text, ENT_QUOTES, 'UTF-8');

$fatal = null;
$ran = false;

if ($expected === '') {
    $fatal = 'SETUP_TOKEN is blank in iced-out-api/.env, so this installer is switched off. '
        . 'Set it to the value the build printed, run this once, then delete this file.';
} elseif (!hash_equals($expected, $supplied)) {
    $fatal = $supplied === ''
        ? 'Add ?token=... to the address. The token is SETUP_TOKEN in iced-out-api/.env.'
        : 'That token does not match SETUP_TOKEN in iced-out-api/.env.';
} else {
    try {
        /** @var Config $config */
        $config = $container->get(Config::class);
        /** @var Database $db */
        $db = $container->get(Database::class);

        /* 1. The database itself. On shared hosting it is created in cPanel —
              this only checks that the credentials in .env reach it, because
              "wrong password" and "wrong database name" are the two failures
              that actually happen and a PDO stack trace names neither. */
        try {
            $db->pdo();
        } catch (Throwable $error) {
            throw new RuntimeException(sprintf(
                'Could not connect to MySQL as %s@%s:%d/%s. Check DB_HOST, DB_NAME, DB_USER and '
                . 'DB_PASS in iced-out-api/.env, and that the user is attached to the database in '
                . 'cPanel -> MySQL Databases with ALL PRIVILEGES. (%s)',
                $config->string('database.user', 'root'),
                $config->string('database.host', '127.0.0.1'),
                $config->int('database.port', 3306),
                $config->string('database.name', 'iced_out'),
                $error->getMessage(),
            ));
        }

        $note(sprintf(
            'Connected to %s on %s.',
            $config->string('database.name', 'iced_out'),
            $db->flavour(),
        ));

        /* 2. The schema. Forward-only and checksummed, so re-running is a no-op
              once every migration has been applied. */
        $applied = (new Migrator($db, $root . '/migrations'))->migrate($note);
        $note($applied === 0
            ? 'Schema already current - nothing to migrate.'
            : sprintf('Applied %d migration(s).', $applied));

        /* 3. Starting data, gated on the registers an install cannot function
              without. Checking every one of them, rather than a single sentinel
              table, is what tells a fresh install from a half-seeded one — a
              half-seeded store never heals, because `users` having rows made
              the seed skip while `products` stayed empty. */
        $core = ['roles', 'permissions', 'users', 'store_settings', 'warehouses', 'stock_items', 'products'];
        $missing = [];

        foreach ($core as $table) {
            $count = $db->selectOne(sprintf('SELECT COUNT(*) AS n FROM %s', $table));

            if ($count === null || (int) $count['n'] === 0) {
                $missing[] = $table;
            }
        }

        $directories = $wantsDemo ? [$root . '/seeds', $root . '/seeds/demo'] : [$root . '/seeds'];

        if ($missing === [] && !$wantsDemo) {
            $note('Starting data already present - seeds skipped.');
        } else {
            if ($missing !== []) {
                $note(sprintf('Empty: %s - seeding.', implode(', ', $missing)));
            }

            $count = (new Seeder($container, $directories))->run($note);
            $note(sprintf('Ran %d seed file(s).', $count));
        }

        /* 4. The directories PHP has to be able to write into. A read-only
              storage/ shows up much later as sessions that will not persist and
              uploads that vanish, which looks like anything but a permission. */
        foreach (['storage/logs', 'storage/cache', 'storage/media'] as $relative) {
            $path = $root . '/' . $relative;

            if (!is_dir($path)) {
                @mkdir($path, 0775, true);
            }

            $note(sprintf('%s %s', is_writable($path) ? 'Writable:' : 'NOT WRITABLE:', $relative));
        }

        $ran = true;
    } catch (Throwable $error) {
        $fatal = $error->getMessage();
    }
}

http_response_code($fatal === null ? 200 : 500);
header('Content-Type: text/html; charset=utf-8');
header('X-Robots-Tag: noindex, nofollow');

?>
<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Iced_out - install</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; padding: 2.5rem 1.25rem; background: #0b0b0c; color: #e8e8ea;
         font: 15px/1.6 ui-monospace, Menlo, Consolas, monospace; }
  main { max-width: 46rem; margin: 0 auto; }
  h1 { font-size: 1.35rem; letter-spacing: .02em; margin: 0 0 .35rem; }
  p.sub { color: #8b8b93; margin: 0 0 2rem; }
  pre { background: #141416; border: 1px solid #26262b; border-radius: 8px;
        padding: 1rem 1.15rem; overflow-x: auto; white-space: pre-wrap; margin: 0 0 1.5rem; }
  .bad { border-color: #7a2b2b; background: #1d1113; color: #ffb4b4; }
  .good { border-color: #2b5f3a; background: #101a13; }
  .warn { border: 1px solid #7a5a1f; background: #1c1710; color: #ffd79a;
          border-radius: 8px; padding: 1rem 1.15rem; }
  code { color: #9fd0ff; }
</style>
<main>
  <h1>Iced_out - install</h1>
  <p class="sub">iced-out.node2begin.com</p>

<?php if ($fatal !== null) { ?>
  <pre class="bad"><?= $html($fatal) ?></pre>
<?php } ?>

<?php if ($lines !== []) { ?>
  <pre class="<?= $ran ? 'good' : '' ?>"><?= $html(implode("\n", $lines)) ?></pre>
<?php } ?>

<?php if ($ran) { ?>
  <div class="warn">
    <strong>Done. Now delete this file.</strong><br>
    Remove <code>setup.php</code> from the document root, and blank
    <code>SETUP_TOKEN</code> in <code>iced-out-api/.env</code>.
    Everything it does is destructive in the wrong hands.
  </div>
<?php } ?>
</main>
