"use client";

import { ArrowRight, Boxes, Check, ClipboardList, CloudOff, MapPin, MoveRight, ScanLine, Search, Truck, Warehouse } from "lucide-react";
import { useState, type FormEvent } from "react";

export type InventoryOperationsView = "movements" | "counts" | "transfers" | "warehouses";

export function InventoryOperations({ view }: { view: InventoryOperationsView }) {
  const [queued, setQueued] = useState(3);
  const [lastScan, setLastScan] = useState("");
  function scan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setLastScan(String(data.get("sku") ?? "")); setQueued((value) => value + 1); event.currentTarget.reset(); }

  if (view === "counts") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Inventory / Cycle count</p><h1>Count what is there.</h1><span>Queued local scans remain visible during a brief network loss; posting always waits for authoritative revalidation.</span></div><span className="warehouse-shift"><CloudOff size={14} /> Offline queue simulated · {queued}</span></div><div className="count-workspace"><form onSubmit={scan}><ScanLine size={34} /><p className="eyebrow">Location BLR-A-04</p><h2>Scan SKU, then count.</h2><label><input autoFocus name="sku" aria-label="Scan inventory SKU" placeholder="ADH-BLK-L" required /><button type="submit">Queue scan</button></label>{lastScan && <div className="scan-feedback is-success"><Check size={18} /><p><strong>{lastScan} queued locally</strong><small>Nothing posted to authoritative inventory.</small></p></div>}</form><aside><header><ClipboardList size={18} /><div><span>Count sheet</span><strong>COUNT-041</strong></div></header>{["ADH-BLK-L · 08", "CHT-INK-M · 18", "BUO-BON-XS · 00"].map((item, index) => <div key={item}><span>{String(index + 1).padStart(2,"0")}</span><strong>{item}</strong><small>{index < 2 ? "Queued" : "Variance"}</small></div>)}<button type="button" disabled>Post after reconnect</button></aside></div></section>;

  if (view === "transfers") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Inventory / Transfers</p><h1>Move with custody.</h1><span>Every handoff preserves source, destination, SKU quantities, scan evidence, and an immutable movement trail.</span></div><button className="admin-primary" type="button"><MoveRight size={15} /> New transfer</button></div><div className="transfer-board">{[{id:"TRF-084",from:"BLR-01",to:"DEL-01",units:"48 units",state:"In transit"},{id:"TRF-083",from:"BLR-01",to:"MUM-01",units:"22 units",state:"Ready to dispatch"},{id:"TRF-081",from:"DEL-01",to:"BLR-01",units:"06 units",state:"Received"}].map((item) => <article key={item.id}><span>{item.id}</span><div><Warehouse size={19} /><strong>{item.from}</strong></div><i><Truck size={18} /></i><div><MapPin size={19} /><strong>{item.to}</strong></div><p>{item.units}<small>{item.state}</small></p><button aria-label={`Open ${item.id}`} type="button"><ArrowRight size={15} /></button></article>)}</div></section>;

  if (view === "warehouses") return <section className="admin-workspace"><div className="admin-heading"><p>Inventory / Network</p><h1>Warehouse scopes.</h1><span>Capacity, provider cutoffs, active waves, stock health, and permission scope by location.</span></div><div className="warehouse-network"><article className="is-primary"><span><i className="status-dot" /> Primary · Online</span><Warehouse size={34} /><h2>BLR-01</h2><p>Bengaluru fulfilment centre</p><div><strong>1,248</strong><small>available units</small></div><div><strong>82%</strong><small>capacity used</small></div><footer>Blue Dart cutoff · 18:00</footer></article><article><span><i className="status-dot" /> Online</span><Warehouse size={34} /><h2>DEL-01</h2><p>Delhi regional node</p><div><strong>486</strong><small>available units</small></div><div><strong>61%</strong><small>capacity used</small></div><footer>Delhivery cutoff · 17:30</footer></article><aside><MapPin size={22} /><h2>Scoped visibility</h2><p>Warehouse roles see assigned locations and tasks only. Cross-location transfers require explicit permission.</p><button type="button">Review staff scope</button></aside></div></section>;

  return <section className="admin-workspace"><div className="admin-heading"><p>Inventory / Immutable ledger</p><h1>Movement history.</h1><span>Corrections append a reasoned adjustment; no row is edited or silently removed.</span></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label="Search inventory movements" placeholder="Movement, SKU, order, transfer" /></label><button type="button">Type · All movements</button><button type="button">Warehouse · BLR-01</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Movement</th><th>SKU</th><th>Type</th><th>Quantity</th><th>Reference</th><th>Actor / time</th></tr></thead><tbody>{[{id:"MOV-8841",sku:"ADH-BLK-L",type:"Order reservation",qty:"−1",ref:"IO-2026-1048",actor:"System · 14:32"},{id:"MOV-8838",sku:"CHT-INK-M",type:"Receipt",qty:"+24",ref:"PO-0184",actor:"Mira P. · 11:06"},{id:"MOV-8832",sku:"BUO-BON-XS",type:"QC quarantine",qty:"−1",ref:"ret-069",actor:"Rohan S. · 10:18"}].map((item) => <tr key={item.id}><td><strong>{item.id}</strong></td><td>{item.sku}</td><td>{item.type}</td><td><strong>{item.qty}</strong></td><td>{item.ref}</td><td>{item.actor}</td></tr>)}</tbody></table></div><div className="admin-action-bar"><p><Boxes size={14} /> Available stock is served by the inventory projection, never reconstructed from this table in the browser.</p><button type="button">Request adjustment</button></div></section>;
}
