"use client";

import { ArrowRight, Check, CircleAlert, ExternalLink, FileText, GripVertical, Link2, Navigation, Plus, Search, ShieldCheck } from "lucide-react";
import { useState } from "react";

export type CmsOperationsView = "pages" | "navigation" | "redirects";

export function CmsOperations({ view }: { view: CmsOperationsView }) {
  const [nav, setNav] = useState(["New drop", "Men", "Women", "Collections", "Sale", "About", "Contact"]);
  if (view === "pages") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>CMS / Editorial pages</p><h1>Page library.</h1><span>Typed About, Contact, and policy content with locale, SEO, version, schedule, and publish readiness.</span></div><button className="admin-primary" type="button"><Plus size={15} /> New policy page</button></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label="Search CMS pages" placeholder="Title, route, locale" /></label><button type="button">State · All</button><button type="button">Locale · en-IN</button></div><div className="cms-page-library">{[{title:"About",route:"/about",type:"Brand page",version:"v8",state:"Published",note:"Updated 02 Aug"},{title:"Contact",route:"/contact",type:"Support entry",version:"v5",state:"Published",note:"Updated 04 Aug"},{title:"Shipping policy",route:"/pages/shipping-policy",type:"Policy",version:"v12",state:"Review",note:"Legal approval pending"},{title:"Return policy",route:"/pages/return-policy",type:"Policy",version:"v10",state:"Published",note:"Effective 01 Aug"},{title:"Privacy",route:"/pages/privacy",type:"Policy",version:"v14",state:"Published",note:"Effective 01 Jul"}].map((item) => <article key={item.route}><FileText size={20} /><div><span>{item.type} · {item.version}</span><h2>{item.title}</h2><p>{item.route} · {item.note}</p></div><span className={`admin-status ${item.state === "Published" ? "admin-status--captured" : "admin-status--review"}`}>{item.state}</span><button type="button"><ArrowRight size={15} /></button></article>)}</div></section>;

  if (view === "navigation") return <section className="admin-workspace"><div className="admin-heading"><p>CMS / Navigation</p><h1>Keep every path intentional.</h1><span>Approved public destinations, link validation, ordering, locale labels, and a separate utility navigation.</span></div><div className="navigation-editor"><main><header><div><Navigation size={19} /><p><span>Primary navigation</span><strong>Desktop + mobile</strong></p></div><button type="button"><Plus size={14} /> Add link</button></header>{nav.map((item, index) => <article key={item}><GripVertical size={16} /><span>0{index + 1}</span><input aria-label={`Navigation label ${index + 1}`} value={item} onChange={(event) => setNav((items) => items.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} /><code>/{item.toLowerCase().replaceAll(" ", "-")}</code><Check size={15} /></article>)}</main><aside><ShieldCheck size={23} /><h2>Navigation contract</h2><p>Categories remain internal catalog classification. Only the seven approved public destinations appear at the top level.</p><div><span>Broken links</span><strong>00</strong></div><div><span>Missing locale labels</span><strong>00</strong></div><button type="button">Preview navigation</button></aside></div></section>;

  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>CMS / Redirect registry</p><h1>Move traffic safely.</h1><span>Validated internal targets, loop detection, hit visibility, schedule, and explicit permanent or temporary intent.</span></div><button className="admin-primary" type="button"><Link2 size={15} /> New redirect</button></div><div className="redirect-health"><article><Check size={18} /><span>Active redirects</span><strong>18</strong></article><article><CircleAlert size={18} /><span>Draft conflicts</span><strong>01</strong></article><article><ExternalLink size={18} /><span>Hits / 30 days</span><strong>4,842</strong></article></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Source</th><th>Destination</th><th>Type</th><th>Hits</th><th>State</th></tr></thead><tbody><tr><td><code>/drop</code></td><td><code>/new-drop</code></td><td>308 permanent</td><td>2,418</td><td><span className="admin-status admin-status--captured">Active</span></td></tr><tr><td><code>/returns</code></td><td><code>/pages/return-policy</code></td><td>308 permanent</td><td>1,204</td><td><span className="admin-status admin-status--captured">Active</span></td></tr><tr><td><code>/winter-preview</code></td><td><code>/collections/after-hours</code></td><td>307 scheduled</td><td>—</td><td><span className="admin-status admin-status--review">Draft</span></td></tr></tbody></table></div></section>;
}
