"use client";

import { ArrowDown, ArrowUp, Clock3, Copy, Eye, GripVertical, Image as ImageIcon, LayoutTemplate, Plus, Save, Type } from "lucide-react";
import { useState } from "react";

const initialBlocks = [
  { id: "hero-001", type: "Hero", title: "Cold by nature.", icon: ImageIcon, state: "Ready" },
  { id: "rail-new", type: "Product rail", title: "Built in shadow.", icon: LayoutTemplate, state: "Ready" },
  { id: "story-001", type: "Brand story", title: "Built in the quiet.", icon: Type, state: "Ready" },
  { id: "services", type: "Service strip", title: "Shipping · Returns · Security", icon: LayoutTemplate, state: "Ready" },
];

export function CmsWorkspace() {
  const [blocks, setBlocks] = useState(initialBlocks);
  function move(index: number, direction: -1 | 1) { const next = [...blocks]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setBlocks(next); }
  return <section className="cms-workspace"><header><div><p>CMS / Home / Draft v12</p><h1>Compose the signal.</h1><span>Typed blocks, validated targets, scheduled publication, and reversible versions.</span></div><div><button type="button"><Eye size={15} /> Preview</button><button type="button"><Save size={15} /> Save draft</button><button className="admin-primary" type="button"><Clock3 size={15} /> Schedule</button></div></header><div className="cms-layout"><aside><p>Page structure</p><strong>Home / en-IN</strong><nav>{["Home", "About", "Contact", "Shipping policy", "Return policy"].map((page, index) => <button className={index === 0 ? "is-active" : ""} key={page} type="button">{page}<span>{index === 0 ? "Draft" : "Published"}</span></button>)}</nav><button className="cms-add-page" type="button"><Plus size={14} /> Add page</button></aside><main><div className="cms-validation"><span><i className="status-dot" /> All publish gates pass</span><p>Media, alt text, destinations, products, schedule, SEO, and redirects validated.</p></div><div className="cms-blocks">{blocks.map((block, index) => { const Icon = block.icon; return <article key={block.id}><GripVertical size={17} /><div className="cms-block-icon"><Icon size={18} /></div><div><span>{block.type} · {block.id}</span><h2>{block.title}</h2></div><span className="admin-status admin-status--captured">{block.state}</span><div className="cms-block-actions"><button aria-label={`Move ${block.title} up`} onClick={() => move(index, -1)} type="button"><ArrowUp size={14} /></button><button aria-label={`Move ${block.title} down`} onClick={() => move(index, 1)} type="button"><ArrowDown size={14} /></button><button aria-label={`Duplicate ${block.title}`} type="button"><Copy size={14} /></button></div></article>})}</div><button className="cms-add-block" type="button"><Plus size={18} /> Add a validated block</button></main><aside className="cms-inspector"><p>Block inspector</p><h2>Hero / hero-001</h2><label>Eyebrow<input defaultValue="Drop 001 / Limited release" /></label><label>Heading<textarea rows={3} defaultValue="Cold by nature." /></label><label>Primary action<input defaultValue="Shop Drop 001" /></label><label>Alt text<textarea rows={3} defaultValue="Two models wearing oversized black Iced_out streetwear" /></label><div><span>Desktop media</span><strong>hero-drop-001.webp</strong></div><small>Preview data only. Publishing remains an audited API operation.</small></aside></div></section>;
}
