import type { Product, ProductVariant } from "@/features/02-products/types/product";

const sizes: ProductVariant["size"][] = ["XS", "S", "M", "L", "XL"];

function variants(
  productId: string,
  color: string,
  colorHex: string,
  soldOut: ProductVariant["size"][] = [],
): ProductVariant[] {
  return sizes.map((size, index) => ({
    id: `${productId}-${color.toLowerCase().replaceAll(" ", "-")}-${size.toLowerCase()}`,
    size,
    color,
    colorHex,
    material: "Heavyweight cotton",
    stock: soldOut.includes(size) ? "SOLD_OUT" : index === 3 ? "LOW_STOCK" : "IN_STOCK",
    available: soldOut.includes(size) ? 0 : index === 3 ? 2 : 8 - index,
  }));
}

export const productFixtures: Product[] = [
  {
    id: "afterdark-hoodie",
    slug: "afterdark-hoodie",
    name: "Afterdark Hoodie",
    category: "Heavyweight fleece",
    description: "A dense, garment-washed hoodie cut with a dropped shoulder and deliberate weight.",
    story: "Designed as the anchor of Drop 001—quiet from a distance, exact up close.",
    fabric: "520 GSM brushed cotton fleece",
    care: "Cold wash inside out. Dry flat. Do not bleach.",
    price: 8900,
    compareAtPrice: 10200,
    color: "Washed black",
    badge: "Bestseller",
    imagePosition: "top-left",
    audience: "unisex",
    collection: "Drop 001",
    isNew: false,
    variants: variants("afterdark-hoodie", "Washed black", "#1b1b1b", ["XS"]),
  },
  {
    id: "bone-utility-overshirt",
    slug: "bone-utility-overshirt",
    name: "Bone Utility Overshirt",
    category: "Structured canvas",
    description: "A four-pocket overshirt with a clean collar, boxy body, and hardware built to age.",
    story: "Utility stripped back to its essential lines in the one light tone of the release.",
    fabric: "410 GSM cotton canvas",
    care: "Cold wash separately. Line dry in shade.",
    price: 11400,
    color: "Bone",
    badge: "New",
    imagePosition: "top-right",
    audience: "women",
    collection: "Drop 001",
    isNew: true,
    variants: variants("bone-utility-overshirt", "Bone", "#d8d0c2", ["XS", "XL"]),
  },
  {
    id: "shadow-cargo-02",
    slug: "shadow-cargo-02",
    name: "Shadow Cargo 02",
    category: "Relaxed utility",
    description: "A wide-leg cargo balanced by articulated knees and low-profile storage.",
    story: "Volume without drag, designed for long nights and constant movement.",
    fabric: "360 GSM washed cotton twill",
    care: "Machine wash cold. Wash with similar colours.",
    price: 9800,
    color: "Charcoal",
    imagePosition: "bottom-left",
    audience: "men",
    collection: "After Hours",
    isNew: true,
    variants: variants("shadow-cargo-02", "Charcoal", "#343434", ["S"]),
  },
  {
    id: "core-heavy-tee",
    slug: "core-heavy-tee",
    name: "Core Heavy Tee",
    category: "280 GSM cotton",
    description: "A compact jersey tee with a clean neck, dropped shoulder, and permanent structure.",
    story: "The simplest piece in the uniform, rebuilt until the proportions felt inevitable.",
    fabric: "280 GSM compact cotton jersey",
    care: "Cold wash. Reshape while damp. Dry flat.",
    price: 4600,
    color: "Ink",
    badge: "Core",
    imagePosition: "bottom-right",
    audience: "unisex",
    collection: "Core Uniform",
    isNew: false,
    variants: variants("core-heavy-tee", "Ink", "#151515"),
  },
];
