"use client";

import { Check, ClipboardCheck, Image as ImageIcon, PackageSearch, RotateCcw, ScanLine } from "lucide-react";
import { useState } from "react";

import { adminReturnFixtures } from "@/features/18-returns/data/admin-return-fixtures";

export function AdminReturnsWorkspace({ view = "requests" }: { view?: "requests" | "qc" | "exchanges" }) {
  const [checks, setChecks] = useState([false, false, false]);
  if (view === "qc") return <section className="admin-workspace"><div className="admin-heading"><p>Returns / Warehouse QC</p><h1>Inspect the evidence.</h1><span>Scan, compare, record evidence, decide condition, and declare the exact stock outcome.</span></div><div className="return-qc-layout"><section><div className="return-qc-scan"><ScanLine size={30} /><div><span>Scanned return</span><strong>ret-069 · IO-2026-1018</strong><small>Afterdark Hoodie · Washed black / M</small></div></div><div className="return-qc-checks">{["SKU and variant match the request", "Wear, wash, odour, and damage inspected", "Customer evidence compared with received item"].map((label, index) => <label key={label}><input checked={checks[index]} onChange={() => setChecks((values) => values.map((value, itemIndex) => itemIndex === index ? !value : value))} type="checkbox" /><span>{checks[index] ? <Check size={15} /> : <ClipboardCheck size={15} />}{label}</span></label>)}</div><div className="return-qc-actions"><button type="button" disabled={!checks.every(Boolean)}>Pass · restock</button><button type="button" disabled={!checks.every(Boolean)}>Partial · quarantine</button><button type="button" disabled={!checks.every(Boolean)}>Fail · no stock</button></div></section><aside><ImageIcon size={25} /><h2>Evidence panel</h2><p>Customer uploads and warehouse photos remain quarantined until validation passes.</p><div><span>Customer evidence</span><strong>02 images</strong></div><div><span>Required QC evidence</span><strong>Not captured</strong></div></aside></div></section>;
  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Returns / {view}</p><h1>{view === "exchanges" ? "Exchange reservations" : "Return requests"}</h1><span>Eligibility, evidence, customer history, reverse pickup, QC, and money outcome stay linked.</span></div><button className="admin-primary" type="button">Create assisted return</button></div><div className="return-operation-grid">{adminReturnFixtures.map((item) => <article key={item.id}><RotateCcw size={19} /><span>{item.id} · {item.order}</span><h2>{item.item}</h2><p>{item.reason}</p><div><strong>{item.outcome}</strong><span className="admin-status admin-status--review">{item.state}</span></div><button type="button"><PackageSearch size={15} /> Open evidence</button></article>)}</div></section>;
}
