import { ArrowDownRight, ArrowUpRight, Download, Info, Search } from "lucide-react";

export type AnalyticsReportView = "sales" | "products" | "customers" | "inventory" | "returns" | "search" | "shipping" | "support";

const reportContent: Record<AnalyticsReportView, { title: string; copy: string; metrics: Array<[string,string,string]>; rows: Array<[string,string,string,string]> }> = {
  sales: { title:"Sales and margin", copy:"Net revenue, order value, discount, tax, refunds, and contribution by verified period.", metrics:[["Net revenue","₹28.4L","+12.4%"],["Orders","707","+10.3%"],["AOV","₹8,925","+3.2%"]], rows:[["Drop 001","₹12,84,600","184","42%"],["Core Uniform","₹9,42,800","296","33%"],["After Hours","₹6,15,200","227","25%"]] },
  products: { title:"Product performance", copy:"Sell-through, size curve, view-to-bag, wishlist, and return-adjusted product value.", metrics:[["Sell-through","68%","+8.1 pts"],["View → bag","14.2%","+1.8 pts"],["Wishlist → order","18.6%","+2.4 pts"]], rows:[["Afterdark Hoodie","₹8,42,600","82%","8.4%"],["Bone Utility Overshirt","₹6,28,400","64%","12.1%"],["Core Heavy Tee","₹4,82,200","71%","6.8%"]] },
  customers: { title:"Customer cohorts", copy:"Acquisition, verified conversion, repeat purchase, lifetime value, and consent-aware segments.", metrics:[["New customers","428","+9.8%"],["Repeat rate","31.4%","+4.2 pts"],["Median LTV","₹18,600","+6.1%"]], rows:[["First order · Aug","184","₹9,420","22%"],["Repeat · 90 days","96","₹16,840","44%"],["Drop 001 early access","72","₹22,610","61%"]] },
  inventory: { title:"Inventory health", copy:"Available stock, reservations, sell-through, cover, low-stock exposure, and warehouse variance.", metrics:[["Available","1,248","−4.2%"],["Reserved","184","+18.7%"],["At risk SKUs","23","6 out"]], rows:[["ADH-BLK-L","2 available","1.2 days","Low"],["BUO-BON-XS","0 available","0 days","Out"],["CHT-INK-M","15 available","18 days","Healthy"]] },
  returns: { title:"Returns and fit", copy:"Reason distribution, size feedback, eligibility, QC outcome, refund time, and product correlation.", metrics:[["Return rate","11.2%","+0.5 pts"],["Fit-related","38%","−2.1 pts"],["Median refund","3.4 days","−0.8 day"]], rows:[["Size / fit","84","38%","92% approved"],["Changed mind","58","26%","88% approved"],["Quality concern","31","14%","61% approved"]] },
  search: { title:"Search intent", copy:"Terms, zero-result queries, refinement, product discovery, and search-to-order value.", metrics:[["Searches","8,420","+16.2%"],["Zero results","4.8%","−1.4 pts"],["Search conversion","6.2%","+0.8 pts"]], rows:[["black hoodie","1,204","0.2% zero","₹4.8L"],["overshirt","842","0.6% zero","₹3.1L"],["jacket","618","8.2% zero","₹1.4L"]] },
  shipping: { title:"Shipping reliability", copy:"Courier pickup, in-transit SLA, NDR, reattempt, RTO, and delivery promise accuracy.", metrics:[["On-time","94.8%","+1.7 pts"],["NDR rate","3.1%","−0.6 pts"],["RTO rate","1.4%","−0.2 pts"]], rows:[["Blue Dart","96.2% on-time","2.4% NDR","1.0% RTO"],["Delhivery","93.8% on-time","3.2% NDR","1.5% RTO"],["Ecom Express","91.4% on-time","4.8% NDR","2.1% RTO"]] },
  support: { title:"Support quality", copy:"First response, resolution, SLA, reopen, channel demand, knowledge deflection, and CSAT.", metrics:[["First response","8m 42s","−2m 18s"],["SLA met","92.6%","+3.4 pts"],["CSAT","4.72 / 5","+0.18"]], rows:[["Delivery","184 tickets","89% SLA","4.61 CSAT"],["Payment","96 tickets","94% SLA","4.78 CSAT"],["Product / fit","82 tickets","97% SLA","4.84 CSAT"]] },
};

export function AnalyticsReport({ view }: { view: AnalyticsReportView }) {
  const report = reportContent[view];
  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Analytics / {view}</p><h1>{report.title}.</h1><span>{report.copy}</span></div><button className="admin-primary" type="button"><Download size={15} /> Export permitted rows</button></div><div className="report-context"><span><i className="status-dot" /> Fresh 14:40 IST</span><button type="button">Last 30 days</button><button type="button">India / Primary</button><p><Info size={14} /> Five-minute materialized rollup</p></div><div className="report-kpis">{report.metrics.map(([label,value,change], index) => <article key={label}><span>{label}</span><strong>{value}</strong><small className={change.startsWith("−") ? "is-down" : "is-up"}>{change.startsWith("−") ? <ArrowDownRight size={13} /> : <ArrowUpRight size={13} />}{change}</small><div>{Array.from({length:12}, (_, bar) => <i style={{height:`${18 + ((bar * 11 + index * 17) % 48)}px`}} key={bar} />)}</div></article>)}</div><div className="admin-section-title"><div><h2>Source values</h2><p>Every visual summary remains paired with filterable, accessible rows.</p></div></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label={`Search ${view} report`} placeholder="Filter report rows" /></label><button type="button">Dimension · Primary</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Dimension</th><th>Primary value</th><th>Volume / rate</th><th>Outcome</th></tr></thead><tbody>{report.rows.map((row) => <tr key={row[0]}>{row.map((cell,index) => <td key={cell}>{index === 0 ? <strong>{cell}</strong> : cell}</td>)}</tr>)}</tbody></table></div></section>;
}
