-- Iced_out — Reference data
-- Database: iced_out
-- Generated by `php bin/console.php db:export`. Do not edit by hand:
-- migrations/ is the source of truth, this file is its output.
-- Server: 10.4.32-MariaDB

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- Reference data: RBAC matrix and store settings.
-- Demo accounts are NOT here — run `php bin/console.php seed`.

SET FOREIGN_KEY_CHECKS = 0;

-- schema_migrations (14 rows)
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (1, '0001_platform_identity.sql', 'afbd2a7ffd802fc5f0ac0c56f84430e07ecb27e871a3e2c078d6bed5fd45528e', 11, '2026-08-17 07:34:30.859624');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (2, '0002_catalog.sql', '5bb261f08185d986c282290c398571acc09779bed3da20b128169c625d856050', 8, '2026-08-17 07:34:30.958934');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (3, '0003_inventory.sql', 'a09060a2cf126ab975e482bcb561d5cfc500f6baadce0e2fa85e6d81bd6d6c1c', 8, '2026-08-17 07:34:31.096824');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (4, '0004_cart_coupons_vouchers.sql', '16c3d1e04b08b57903bd689bff97b8b68e2a0f9cdfe7bb4820862ae38ca3a50e', 6, '2026-08-17 07:34:31.162905');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (5, '0005_orders_payments.sql', '96e321780b744fc9e3e7e9506a3b371dc88ba9bb230a6e8759110f713a7ea5ba', 12, '2026-08-17 07:34:31.387304');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (6, '0006_shipping_tracking.sql', '4791f7a80c3aaa6553dccfd06dff7cf259213fdeeb04ab0c5058d74647f54127', 5, '2026-08-17 07:34:31.452180');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (7, '0007_returns_reviews_support.sql', '09ddb5756cbb20390060db0760e2e4c38843e1fa8df1b0e4ebdcea7f8e2186b2', 7, '2026-08-17 07:34:31.552679');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (8, '0008_cms_settings_platform.sql', '472522f08112fa51e0e0fa9aefc1129e34fd72e9f7beec66145a15eade902eea', 11, '2026-08-17 07:34:31.702321');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (9, '0009_analytics_dashboard.sql', '7196bc239f873acf88ce2802207c8d5e5f8c9f72f119e0d9b6afbb4fe2c56f10', 3, '2026-08-17 07:34:31.740745');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (10, '0010_views.sql', '590bede9a4b3a60d70694066f6eb5d1810a640a7ee176efe28ebf078ebc220a8', 3, '2026-08-17 07:34:31.764209');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (11, '0011_catalog_console_fields.sql', '7e1ab64d473f3fde014d59e3563bbeba66c708c574f5615ccbb07b8b43311b74', 2, '2026-08-17 07:34:31.816513');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (12, '0012_orders_optional_account.sql', '5f2bac4ab5aaafa05d5ad499484f62bab6a16b7cb9e145d8fa1e2298ef4eb1a9', 3, '2026-08-17 07:34:31.877742');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (13, '0013_vocabularies_out_of_the_schema.sql', '2ab5a5d73eb51b098b0cbd6cf55c879bb66812aa14a31c991094dcb1b7c4a107', 6, '2026-08-17 07:34:31.896345');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (14, '0014_item_photos.sql', '69eb924f84309ac6ef7a13990f8d00b682738b24738997c80dce96c54e466707', 4, '2026-08-17 07:34:31.960549');

-- roles (4 rows)
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (1, 'ADMIN', 1);
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (2, 'MANAGER', 1);
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (3, 'SUPPORT', 1);
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (4, 'WAREHOUSE', 1);

-- permissions (28 rows)
INSERT INTO `permissions` (`id`, `code`) VALUES (28, '*');
INSERT INTO `permissions` (`id`, `code`) VALUES (26, 'audit.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (7, 'catalog.edit');
INSERT INTO `permissions` (`id`, `code`) VALUES (8, 'catalog.publish');
INSERT INTO `permissions` (`id`, `code`) VALUES (6, 'catalog.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (14, 'coupons.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (21, 'customers.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (20, 'customers.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (1, 'dashboard.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (10, 'inventory.adjust');
INSERT INTO `permissions` (`id`, `code`) VALUES (11, 'inventory.transfer');
INSERT INTO `permissions` (`id`, `code`) VALUES (9, 'inventory.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (27, 'media.upload');
INSERT INTO `permissions` (`id`, `code`) VALUES (3, 'orders.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (2, 'orders.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (17, 'payments.exports.create');
INSERT INTO `permissions` (`id`, `code`) VALUES (16, 'payments.reconcile');
INSERT INTO `permissions` (`id`, `code`) VALUES (15, 'payments.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (19, 'refunds.approve');
INSERT INTO `permissions` (`id`, `code`) VALUES (18, 'refunds.request');
INSERT INTO `permissions` (`id`, `code`) VALUES (24, 'reports.operational.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (13, 'returns.approve');
INSERT INTO `permissions` (`id`, `code`) VALUES (12, 'returns.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (22, 'reviews.moderate');
INSERT INTO `permissions` (`id`, `code`) VALUES (25, 'settings.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (5, 'shipping.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (4, 'shipping.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (23, 'support.tickets.manage');

-- role_permissions (40 rows)
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (1, 28);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 1);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 2);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 3);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 4);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 5);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 6);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 7);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 8);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 9);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 10);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 11);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 12);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 13);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 14);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 15);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 16);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 18);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 20);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 21);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 22);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 23);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 24);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 27);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 1);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 2);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 4);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 12);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 15);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 20);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 22);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 23);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 1);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 2);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 4);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 5);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 9);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 10);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 11);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 12);

-- store_settings (15 rows)
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (1, 'delivery', '{\"standard_fee\":199,\"express_fee\":499,\"free_over\":4999,\"standard_window\":[3,5],\"express_window\":[1,2]}', 1, NULL, '2026-08-17 07:34:31.983762');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (2, 'cod', '{\"max\":5000,\"fee\":0,\"waive_over\":null}', 1, NULL, '2026-08-17 07:34:31.984083');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (3, 'inventory', '{\"low_stock_at\":4,\"reservation_ttl_prepaid\":900,\"reservation_ttl_cod\":600,\"max_per_order\":3,\"categories\":[\"Top\",\"Bottom\"],\"sizes_by_category\":{\"Top\":[\"S\",\"M\",\"L\",\"XL\",\"XXL\"],\"Bottom\":[\"30\",\"32\",\"34\",\"36\",\"38\",\"40\",\"42\"]},\"types_by_category\":{\"Top\":[\"T-shirt\",\"Shirt\",\"Hoodie\",\"Overshirt\",\"Jacket\"],\"Bottom\":[\"Jeans\",\"Cargo\",\"Casual\",\"Joggers\",\"Shorts\"]}}', 1, NULL, '2026-08-17 07:34:31.984458');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (4, 'shipping', '{\"providers\":[\"Blue Dart\",\"Delhivery\",\"Ecom Express\"],\"fail_reasons\":[\"Nobody was home\",\"Address was wrong\",\"Customer said no\",\"Could not reach the customer\",\"Not shared yet\"],\"max_delivery_attempts\":3,\"handling_states\":[\"Needs action\",\"Sending back\",\"Back in store\"]}', 1, NULL, '2026-08-17 07:34:31.986211');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (5, 'returns', '{\"reasons\":[\"Size / fit\",\"Changed mind\",\"Quality concern\",\"Wrong item\",\"Damaged in transit\"],\"outcomes\":[\"Voucher\",\"Exchange\"],\"window_days\":14}', 1, NULL, '2026-08-17 07:34:31.986607');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (6, 'payments', '{\"gateways\":[\"Razorpay\",\"Stripe\",\"Cashfree\",\"On device\",\"Courier\"],\"refund_reasons\":[\"Return approved\",\"Order cancelled\",\"Payment mismatch\",\"Goodwill\"],\"methods\":[\"UPI\",\"Card\",\"Netbanking\",\"Cash on delivery\"]}', 1, NULL, '2026-08-17 07:34:31.987005');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (7, 'catalog', '{\"product_states\":[\"Published\",\"Scheduled\",\"Draft\"],\"collection_states\":[\"Live\",\"Scheduled\",\"Draft\"],\"variant_states\":[\"Active\",\"Low\",\"Out\",\"Archived\"]}', 1, NULL, '2026-08-17 07:34:31.987268');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (8, 'media', '{\"max_bytes_console\":8388608,\"max_bytes_customer\":5242880,\"max_bytes_staff_photo\":2097152,\"allowed_mime\":[\"image/jpeg\",\"image/png\",\"image/webp\"],\"max_edge\":1600,\"quality\":82}', 1, NULL, '2026-08-17 07:34:31.987514');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (9, 'security', '{\"login_lockout_after\":20,\"login_lockout_window\":900,\"idempotency_ttl_hours\":48}', 1, NULL, '2026-08-17 07:34:31.987756');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (10, 'sessions', '{\"customer_ttl\":2592000,\"staff_idle_ttl\":900}', 1, NULL, '2026-08-17 07:34:31.988004');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (11, 'id_pools', '{\"order\":{\"prefix\":\"ord-local-\",\"width\":2,\"from\":1,\"to\":30},\"tracking\":{\"prefix\":\"track-local-\",\"width\":2,\"from\":1,\"to\":30},\"payment\":{\"prefix\":\"pay_ICE\",\"width\":4,\"from\":2001,\"to\":2030},\"customer\":{\"prefix\":\"cus-\",\"width\":4,\"from\":2050,\"to\":2079}}', 1, NULL, '2026-08-17 07:34:31.988258');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (12, 'id_series', '{\"shipment\":{\"prefix\":\"shp-\",\"width\":0,\"from\":1051},\"pickup\":{\"prefix\":\"PICK-\",\"width\":4,\"from\":413},\"review\":{\"prefix\":\"REV-\",\"width\":0,\"from\":2001},\"support\":{\"prefix\":\"IO-Q-\",\"width\":0,\"from\":1004},\"return\":{\"prefix\":\"ret-\",\"width\":3,\"from\":1},\"refund\":{\"prefix\":\"ref_ICE\",\"width\":3,\"from\":1},\"stock_item\":{\"prefix\":\"ITM-\",\"width\":3,\"from\":1},\"transfer\":{\"prefix\":\"TRF-\",\"width\":3,\"from\":1},\"voucher\":{\"prefix\":\"IOV\",\"width\":3,\"from\":1}}', 1, NULL, '2026-08-17 07:34:31.988524');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (13, 'order_number', '{\"prefix\":\"IO-2026-\",\"next_serial\":1049}', 1, NULL, '2026-08-17 07:34:31.988800');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (14, 'support', '{\"topics\":[\"Delivery\",\"Return or exchange\",\"Payment or refund\",\"Product and fit\",\"Something else\"],\"no_order_label\":\"No order\",\"slas\":{\"first_response_hours\":24,\"resolution_hours\":72}}', 1, NULL, '2026-08-17 07:34:31.989053');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (15, 'business', '{\"name\":\"Iced_out\",\"support_email\":\"help@iced-out.example\",\"gstin\":\"\",\"tax_rates\":[]}', 1, NULL, '2026-08-17 07:34:31.989423');

SET FOREIGN_KEY_CHECKS = 1;
