-- Iced_out — Schema
-- Database: iced_out
-- Generated by `php bin/console.php db:export`. Do not edit by hand:
-- migrations/ is the source of truth, this file is its output.
-- Server: 10.4.32-MariaDB

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE DATABASE IF NOT EXISTS `iced_out` DEFAULT CHARACTER SET utf8mb4;
USE `iced_out`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `activity_feed`;
CREATE TABLE `activity_feed` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `source` varchar(24) NOT NULL,
  `action` varchar(40) NOT NULL,
  `title` varchar(160) NOT NULL,
  `detail` varchar(255) NOT NULL DEFAULT '',
  `actor` varchar(80) NOT NULL DEFAULT '',
  `state` varchar(40) NOT NULL DEFAULT '',
  `tone` varchar(8) NOT NULL DEFAULT 'info',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_activity_feed_created` (`id`,`created_at`),
  CONSTRAINT `ck_activity_feed_source` CHECK (`source` in ('Orders','Payments','Shipping','Inventory','Returns','Support')),
  CONSTRAINT `ck_activity_feed_tone` CHECK (`tone` in ('good','warn','bad','info'))
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `audit_logs`;
CREATE TABLE `audit_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `actor_id` bigint(20) unsigned DEFAULT NULL,
  `actor_role` varchar(32) NOT NULL DEFAULT '',
  `permission_used` varchar(64) NOT NULL DEFAULT '',
  `action` varchar(160) NOT NULL DEFAULT '',
  `entity_type` varchar(60) NOT NULL DEFAULT '',
  `entity_id` varchar(64) NOT NULL DEFAULT '',
  `before_json` mediumtext DEFAULT NULL,
  `after_json` mediumtext DEFAULT NULL,
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `ip` varchar(45) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_audit_logs_actor` (`actor_id`,`created_at`),
  KEY `ix_audit_logs_entity` (`entity_type`,`entity_id`),
  KEY `ix_audit_logs_request` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `auth_tokens`;
CREATE TABLE `auth_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `purpose` varchar(24) NOT NULL,
  `token_hash` binary(32) NOT NULL,
  `payload_json` text DEFAULT NULL,
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `expires_at` datetime(6) NOT NULL,
  `consumed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_auth_tokens_hash` (`token_hash`),
  KEY `ix_auth_tokens_user` (`user_id`,`purpose`),
  CONSTRAINT `fk_auth_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_auth_tokens_purpose` CHECK (`purpose` in ('PASSWORD_RESET','EMAIL_VERIFY','BAG_INTENT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cart_items`;
CREATE TABLE `cart_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `cart_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `variant_size` varchar(8) NOT NULL,
  `quantity` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `price_at_add` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cart_items_line` (`cart_id`,`product_id`,`variant_size`),
  KEY `ix_cart_items_product` (`product_id`),
  CONSTRAINT `fk_cart_items_cart` FOREIGN KEY (`cart_id`) REFERENCES `carts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cart_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_cart_items_quantity` CHECK (`quantity` between 1 and 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `carts`;
CREATE TABLE `carts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
  `coupon_code` varchar(40) DEFAULT NULL,
  `version` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `active_key` varchar(32) GENERATED ALWAYS AS (if(`status` = 'ACTIVE',concat('u',`user_id`),NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_carts_active` (`active_key`),
  KEY `ix_carts_user` (`user_id`,`status`),
  CONSTRAINT `fk_carts_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_carts_status` CHECK (`status` in ('ACTIVE','CONVERTED','ABANDONED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `name` varchar(80) NOT NULL,
  `position` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_categories_public_id` (`public_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `checkout_drafts`;
CREATE TABLE `checkout_drafts` (
  `user_id` bigint(20) unsigned NOT NULL,
  `name` varchar(120) NOT NULL DEFAULT '',
  `email` varchar(190) NOT NULL DEFAULT '',
  `mobile` varchar(20) NOT NULL DEFAULT '',
  `address` varchar(255) NOT NULL DEFAULT '',
  `city` varchar(80) NOT NULL DEFAULT '',
  `state` varchar(80) NOT NULL DEFAULT '',
  `postal_code` varchar(10) NOT NULL DEFAULT '',
  `delivery_method` varchar(16) NOT NULL DEFAULT 'standard',
  `payment_method` varchar(16) NOT NULL DEFAULT 'cod',
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_checkout_drafts_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_checkout_drafts_delivery` CHECK (`delivery_method` in ('standard','express')),
  CONSTRAINT `ck_checkout_drafts_payment` CHECK (`payment_method` in ('cod','card','razorpay'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cms_blocks`;
CREATE TABLE `cms_blocks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `page_id` bigint(20) unsigned NOT NULL,
  `public_id` varchar(40) NOT NULL,
  `type` varchar(24) NOT NULL,
  `position` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `config_json` mediumtext DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cms_blocks_public_id` (`public_id`),
  KEY `ix_cms_blocks_page` (`page_id`,`position`),
  CONSTRAINT `fk_cms_blocks_page` FOREIGN KEY (`page_id`) REFERENCES `cms_pages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_cms_blocks_type` CHECK (`type` in ('hero','signal-strip','product-rail','destination-grid','brand-story','manifesto','service-grid'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cms_page_versions`;
CREATE TABLE `cms_page_versions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `page_id` bigint(20) unsigned NOT NULL,
  `version` int(10) unsigned NOT NULL DEFAULT 1,
  `body_json` mediumtext DEFAULT NULL,
  `published_at` datetime(6) DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cms_page_versions` (`page_id`,`version`),
  KEY `fk_cms_page_versions_author` (`created_by`),
  CONSTRAINT `fk_cms_page_versions_author` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_cms_page_versions_page` FOREIGN KEY (`page_id`) REFERENCES `cms_pages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cms_pages`;
CREATE TABLE `cms_pages` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(80) NOT NULL,
  `title` varchar(160) NOT NULL DEFAULT '',
  `type` varchar(16) NOT NULL DEFAULT 'POLICY',
  `status` varchar(16) NOT NULL DEFAULT 'Draft',
  `current_version_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cms_pages_slug` (`slug`),
  KEY `fk_cms_pages_current_version` (`current_version_id`),
  CONSTRAINT `fk_cms_pages_current_version` FOREIGN KEY (`current_version_id`) REFERENCES `cms_page_versions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_cms_pages_type` CHECK (`type` in ('HOME','POLICY')),
  CONSTRAINT `ck_cms_pages_status` CHECK (`status` in ('Published','Draft'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `collection_products`;
CREATE TABLE `collection_products` (
  `collection_id` bigint(20) unsigned NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `position` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`collection_id`,`product_id`),
  KEY `ix_collection_products_product` (`product_id`),
  CONSTRAINT `fk_collection_products_collection` FOREIGN KEY (`collection_id`) REFERENCES `collections` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_collection_products_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `collections`;
CREATE TABLE `collections` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(80) NOT NULL,
  `name` varchar(120) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'Draft',
  `position` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_collections_public_id` (`public_id`),
  CONSTRAINT `ck_collections_status` CHECK (`status` in ('Live','Scheduled','Draft'))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `contact_messages`;
CREATE TABLE `contact_messages` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `email` varchar(190) NOT NULL,
  `topic` varchar(40) NOT NULL DEFAULT '',
  `message` text NOT NULL,
  `consent` tinyint(1) NOT NULL DEFAULT 0,
  `converted_query_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_contact_messages_created` (`created_at`),
  KEY `fk_contact_messages_query` (`converted_query_id`),
  CONSTRAINT `fk_contact_messages_query` FOREIGN KEY (`converted_query_id`) REFERENCES `support_queries` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `coupon_redemptions`;
CREATE TABLE `coupon_redemptions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `coupon_id` bigint(20) unsigned DEFAULT NULL,
  `voucher_id` bigint(20) unsigned DEFAULT NULL,
  `order_id` bigint(20) unsigned NOT NULL,
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_coupon_redemptions_order` (`order_id`),
  KEY `ix_coupon_redemptions_coupon` (`coupon_id`),
  KEY `ix_coupon_redemptions_voucher` (`voucher_id`),
  CONSTRAINT `fk_coupon_redemptions_coupon` FOREIGN KEY (`coupon_id`) REFERENCES `coupons` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_coupon_redemptions_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_coupon_redemptions_voucher` FOREIGN KEY (`voucher_id`) REFERENCES `vouchers` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_coupon_redemptions_source` CHECK (`coupon_id` is not null or `voucher_id` is not null)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `coupons`;
CREATE TABLE `coupons` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(40) NOT NULL,
  `label` varchar(120) NOT NULL DEFAULT '',
  `kind` varchar(8) NOT NULL DEFAULT 'percent',
  `value` decimal(12,2) NOT NULL DEFAULT 0.00,
  `min_subtotal` decimal(12,2) NOT NULL DEFAULT 0.00,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `starts_at` datetime(6) DEFAULT NULL,
  `ends_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_coupons_code` (`code`),
  CONSTRAINT `ck_coupons_kind` CHECK (`kind` in ('percent','amount'))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `courier_pickups`;
CREATE TABLE `courier_pickups` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(24) NOT NULL,
  `provider` varchar(40) NOT NULL DEFAULT '',
  `parcels` int(10) unsigned NOT NULL DEFAULT 0,
  `pickup_label` varchar(60) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Open',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_courier_pickups_public_id` (`public_id`),
  CONSTRAINT `ck_courier_pickups_status` CHECK (`status` in ('Open','Handed over'))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `domain_events_outbox`;
CREATE TABLE `domain_events_outbox` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `event_id` char(36) NOT NULL,
  `type` varchar(80) NOT NULL,
  `payload_json` mediumtext DEFAULT NULL,
  `occurred_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `processed_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_domain_events_event_id` (`event_id`),
  KEY `ix_domain_events_pending` (`processed_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `faqs`;
CREATE TABLE `faqs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `question` varchar(255) NOT NULL,
  `answer` text NOT NULL,
  `position` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_faqs_active` (`is_active`,`position`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `idempotency_keys`;
CREATE TABLE `idempotency_keys` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `scope` varchar(120) NOT NULL,
  `endpoint` varchar(160) NOT NULL,
  `key_hash` binary(32) NOT NULL,
  `request_hash` binary(32) NOT NULL,
  `response_status` smallint(5) unsigned NOT NULL DEFAULT 200,
  `response_body` mediumtext DEFAULT NULL,
  `expires_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_idempotency_keys` (`scope`,`endpoint`,`key_hash`),
  KEY `ix_idempotency_keys_expiry` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `inbox_messages`;
CREATE TABLE `inbox_messages` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `subject` varchar(160) NOT NULL,
  `preview` varchar(255) NOT NULL DEFAULT '',
  `type` varchar(16) NOT NULL DEFAULT 'Order',
  `sent_at` datetime(6) NOT NULL,
  `read_at` datetime(6) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inbox_messages_user_public` (`user_id`,`public_id`),
  KEY `ix_inbox_messages_user` (`user_id`,`deleted_at`,`sent_at`),
  CONSTRAINT `fk_inbox_messages_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_inbox_messages_type` CHECK (`type` in ('Order','Delivery','Drop','Restock','Support'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `inventory_movements`;
CREATE TABLE `inventory_movements` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `stock_item_id` bigint(20) unsigned DEFAULT NULL,
  `variant_id` bigint(20) unsigned DEFAULT NULL,
  `type` varchar(24) NOT NULL,
  `qty` int(11) NOT NULL,
  `on_hand_after` int(11) DEFAULT NULL,
  `reserved_after` int(11) DEFAULT NULL,
  `reference_type` varchar(32) NOT NULL DEFAULT '',
  `reference_id` varchar(64) NOT NULL DEFAULT '',
  `idempotency_key` varchar(191) DEFAULT NULL,
  `actor_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inventory_movements_idem` (`idempotency_key`),
  KEY `ix_inventory_movements_item` (`stock_item_id`,`created_at`),
  KEY `ix_inventory_movements_variant` (`variant_id`,`created_at`),
  KEY `ix_inventory_movements_reference` (`reference_type`,`reference_id`),
  KEY `fk_inventory_movements_actor` (`actor_id`),
  CONSTRAINT `fk_inventory_movements_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_inventory_movements_item` FOREIGN KEY (`stock_item_id`) REFERENCES `stock_items` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_inventory_movements_variant` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_inventory_movements_type` CHECK (`type` in ('PURCHASE_IN','SALE_RESERVE','SALE_CONFIRM','RESERVE_EXPIRE','RETURN_IN','RTO_IN','TRANSFER_OUT','TRANSFER_IN','ADJUST_UP','ADJUST_DOWN','DAMAGE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `inventory_reservations`;
CREATE TABLE `inventory_reservations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned DEFAULT NULL,
  `order_item_id` bigint(20) unsigned DEFAULT NULL,
  `variant_id` bigint(20) unsigned NOT NULL,
  `qty` int(11) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'HELD',
  `expires_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inventory_reservations_order_item` (`order_item_id`),
  KEY `ix_inventory_reservations_status` (`status`,`expires_at`),
  KEY `ix_inventory_reservations_variant` (`variant_id`),
  KEY `ix_inventory_reservations_order` (`order_id`),
  CONSTRAINT `fk_inventory_reservations_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_reservations_order_item` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inventory_reservations_variant` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_inventory_reservations_status` CHECK (`status` in ('HELD','CONFIRMED','RELEASED','EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `inventory_transfer_items`;
CREATE TABLE `inventory_transfer_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `transfer_id` bigint(20) unsigned NOT NULL,
  `stock_item_id` bigint(20) unsigned NOT NULL,
  `qty` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `ix_transfer_items_transfer` (`transfer_id`),
  KEY `fk_transfer_items_stock_item` (`stock_item_id`),
  CONSTRAINT `fk_transfer_items_stock_item` FOREIGN KEY (`stock_item_id`) REFERENCES `stock_items` (`id`),
  CONSTRAINT `fk_transfer_items_transfer` FOREIGN KEY (`transfer_id`) REFERENCES `inventory_transfers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `inventory_transfers`;
CREATE TABLE `inventory_transfers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(16) NOT NULL,
  `from_warehouse_id` bigint(20) unsigned NOT NULL,
  `to_warehouse_id` bigint(20) unsigned NOT NULL,
  `units` int(10) unsigned NOT NULL DEFAULT 0,
  `dispatched_label` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Ready',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_inventory_transfers_public_id` (`public_id`),
  KEY `ix_inventory_transfers_status` (`status`),
  KEY `fk_inventory_transfers_from` (`from_warehouse_id`),
  KEY `fk_inventory_transfers_to` (`to_warehouse_id`),
  CONSTRAINT `fk_inventory_transfers_from` FOREIGN KEY (`from_warehouse_id`) REFERENCES `warehouses` (`id`),
  CONSTRAINT `fk_inventory_transfers_to` FOREIGN KEY (`to_warehouse_id`) REFERENCES `warehouses` (`id`),
  CONSTRAINT `ck_inventory_transfers_status` CHECK (`status` in ('Ready','In transit','Received','Cancelled')),
  CONSTRAINT `ck_inventory_transfers_route` CHECK (`from_warehouse_id` <> `to_warehouse_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `job_queue`;
CREATE TABLE `job_queue` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(32) NOT NULL DEFAULT 'default',
  `type` varchar(120) NOT NULL,
  `payload_json` mediumtext DEFAULT NULL,
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `run_after` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `locked_by` varchar(64) DEFAULT NULL,
  `locked_at` datetime(6) DEFAULT NULL,
  `done_at` datetime(6) DEFAULT NULL,
  `failed_at` datetime(6) DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_job_queue_claim` (`queue`,`done_at`,`failed_at`,`run_after`),
  KEY `ix_job_queue_locked` (`locked_by`,`locked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `login_attempts`;
CREATE TABLE `login_attempts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `email_normalized` varchar(190) NOT NULL,
  `audience` varchar(16) NOT NULL,
  `ip` varbinary(16) DEFAULT NULL,
  `was_success` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_login_attempts_email` (`email_normalized`,`created_at`),
  KEY `ix_login_attempts_ip` (`ip`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `media_assets`;
CREATE TABLE `media_assets` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `owner_type` varchar(16) NOT NULL,
  `owner_id` bigint(20) unsigned DEFAULT NULL,
  `storage_key` varchar(255) NOT NULL,
  `mime` varchar(64) NOT NULL,
  `bytes` int(10) unsigned NOT NULL DEFAULT 0,
  `width` int(10) unsigned DEFAULT NULL,
  `height` int(10) unsigned DEFAULT NULL,
  `checksum` char(64) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_media_public_id` (`public_id`),
  KEY `ix_media_owner` (`owner_type`,`owner_id`),
  CONSTRAINT `ck_media_owner_type` CHECK (`owner_type` in ('product','review','profile','cms','shipment','stock_item','variant'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `ndr_cases`;
CREATE TABLE `ndr_cases` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `shipment_id` bigint(20) unsigned NOT NULL,
  `reason` varchar(120) NOT NULL DEFAULT '',
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `status` varchar(16) NOT NULL DEFAULT 'Open',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ndr_cases_shipment` (`shipment_id`),
  CONSTRAINT `fk_ndr_cases_shipment` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_ndr_cases_attempts` CHECK (`attempts` <= 3),
  CONSTRAINT `ck_ndr_cases_status` CHECK (`status` in ('Open','Reattempting','RTO','Closed'))
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `notification_preferences`;
CREATE TABLE `notification_preferences` (
  `user_id` bigint(20) unsigned NOT NULL,
  `channel` varchar(16) NOT NULL,
  `topic` varchar(16) NOT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`user_id`,`channel`,`topic`),
  CONSTRAINT `fk_notification_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_notification_channel` CHECK (`channel` in ('email','sms','whatsapp','push')),
  CONSTRAINT `ck_notification_topic` CHECK (`topic` in ('orders','marketing','security'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `ops_signals`;
CREATE TABLE `ops_signals` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `kind` varchar(16) NOT NULL,
  `tone` varchar(8) NOT NULL DEFAULT 'ink',
  `title` varchar(160) NOT NULL,
  `detail` varchar(255) NOT NULL DEFAULT '',
  `href` varchar(190) NOT NULL DEFAULT '',
  `entity_type` varchar(40) NOT NULL DEFAULT '',
  `entity_id` varchar(64) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `cleared_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_ops_signals_open` (`cleared_at`,`created_at`),
  CONSTRAINT `ck_ops_signals_kind` CHECK (`kind` in ('order','payment','shipment','inventory','return','support','review')),
  CONSTRAINT `ck_ops_signals_tone` CHECK (`tone` in ('mint','amber','rose','ink'))
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `order_cancellation_requests`;
CREATE TABLE `order_cancellation_requests` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned NOT NULL,
  `reason` varchar(120) NOT NULL,
  `note` varchar(500) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Received',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_order_cancellation_order` (`order_id`,`status`),
  CONSTRAINT `fk_order_cancellation_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_order_cancellation_status` CHECK (`status` in ('Received','Approved','Rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned NOT NULL,
  `line_public_id` varchar(40) NOT NULL,
  `product_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(160) NOT NULL,
  `variant_label` varchar(120) NOT NULL DEFAULT '',
  `size` varchar(8) NOT NULL DEFAULT '',
  `quantity` int(10) unsigned NOT NULL DEFAULT 1,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `line_total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `tax_rate` decimal(5,2) NOT NULL DEFAULT 0.00,
  `tax_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `return_eligible` tinyint(1) NOT NULL DEFAULT 1,
  `returned_qty` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_order_items_line` (`order_id`,`line_public_id`),
  KEY `ix_order_items_product` (`product_id`),
  CONSTRAINT `fk_order_items_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_order_items_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_order_items_returned` CHECK (`returned_qty` <= `quantity`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `order_status_history`;
CREATE TABLE `order_status_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned NOT NULL,
  `seq` int(10) unsigned NOT NULL,
  `from_status` varchar(24) NOT NULL DEFAULT '',
  `to_status` varchar(24) NOT NULL,
  `actor_type` varchar(16) NOT NULL DEFAULT 'system',
  `actor_id` bigint(20) unsigned DEFAULT NULL,
  `note` varchar(255) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_order_status_history_seq` (`order_id`,`seq`),
  CONSTRAINT `fk_order_status_history_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_order_status_history_actor` CHECK (`actor_type` in ('customer','staff','system'))
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `number` varchar(40) NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'Processing',
  `console_state` varchar(16) NOT NULL DEFAULT 'Placed',
  `cancelled_by` varchar(16) DEFAULT NULL,
  `contact_name` varchar(120) NOT NULL DEFAULT '',
  `contact_email` varchar(190) NOT NULL DEFAULT '',
  `contact_mobile` varchar(20) NOT NULL DEFAULT '',
  `addr_line` varchar(255) NOT NULL DEFAULT '',
  `addr_city` varchar(80) NOT NULL DEFAULT '',
  `addr_state` varchar(80) NOT NULL DEFAULT '',
  `addr_postal` varchar(10) NOT NULL DEFAULT '',
  `delivery_label` varchar(80) NOT NULL DEFAULT '',
  `delivery_estimate` varchar(40) NOT NULL DEFAULT '',
  `delivery_fee` decimal(12,2) NOT NULL DEFAULT 0.00,
  `subtotal` decimal(12,2) NOT NULL DEFAULT 0.00,
  `discount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `coupon_code` varchar(40) DEFAULT NULL,
  `items_summary` text DEFAULT NULL,
  `cancellation_eligible` tinyint(1) NOT NULL DEFAULT 1,
  `placed_at` datetime(6) NOT NULL,
  `version` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_orders_public_id` (`public_id`),
  UNIQUE KEY `uq_orders_number` (`number`),
  KEY `ix_orders_user` (`user_id`,`placed_at`),
  KEY `ix_orders_status` (`status`),
  KEY `ix_orders_console_state` (`console_state`,`placed_at`),
  CONSTRAINT `fk_orders_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_orders_status` CHECK (`status` in ('Processing','Delivered','Payment failed','Cancelled')),
  CONSTRAINT `ck_orders_console_state` CHECK (`console_state` in ('Placed','Confirmed','Cancelled')),
  CONSTRAINT `ck_orders_cancelled_by` CHECK (`cancelled_by` is null or `cancelled_by` in ('Store','Customer'))
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payment_attempts`;
CREATE TABLE `payment_attempts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `payment_id` bigint(20) unsigned NOT NULL,
  `operation` varchar(16) NOT NULL,
  `request_json` mediumtext DEFAULT NULL,
  `response_json` mediumtext DEFAULT NULL,
  `outcome` varchar(24) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_payment_attempts_payment` (`payment_id`,`created_at`),
  CONSTRAINT `fk_payment_attempts_payment` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_payment_attempts_operation` CHECK (`operation` in ('initiate','verify','webhook','capture','refund','check'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `order_id` bigint(20) unsigned NOT NULL,
  `customer_masked` varchar(120) NOT NULL DEFAULT '',
  `gateway` varchar(24) NOT NULL DEFAULT 'Razorpay',
  `method` varchar(40) NOT NULL DEFAULT '',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `status` varchar(16) NOT NULL DEFAULT 'Due',
  `note` varchar(255) NOT NULL DEFAULT '',
  `reference` varchar(120) NOT NULL DEFAULT '',
  `razorpay_order_id` varchar(120) DEFAULT NULL,
  `signature_verified` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payments_public_id` (`public_id`),
  KEY `ix_payments_order` (`order_id`),
  KEY `ix_payments_status` (`status`,`created_at`),
  KEY `ix_payments_reference` (`reference`),
  KEY `ix_payments_razorpay_order` (`razorpay_order_id`),
  CONSTRAINT `fk_payments_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_payments_status` CHECK (`status` in ('Captured','Due','Failed','Refunded'))
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `payouts`;
CREATE TABLE `payouts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `gateway` varchar(24) NOT NULL DEFAULT 'Razorpay',
  `period_label` varchar(60) NOT NULL DEFAULT '',
  `gross` decimal(12,2) NOT NULL DEFAULT 0.00,
  `fees` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `status` varchar(16) NOT NULL DEFAULT 'Pending',
  `paid_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payouts_public_id` (`public_id`),
  CONSTRAINT `ck_payouts_status` CHECK (`status` in ('Pending','Paid'))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_permissions_code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `product_price_history`;
CREATE TABLE `product_price_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` bigint(20) unsigned NOT NULL,
  `price` decimal(12,2) NOT NULL,
  `compare_at_price` decimal(12,2) DEFAULT NULL,
  `changed_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_price_history_product` (`product_id`,`created_at`),
  KEY `fk_price_history_actor` (`changed_by`),
  CONSTRAINT `fk_price_history_actor` FOREIGN KEY (`changed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_price_history_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `product_rating_summaries`;
CREATE TABLE `product_rating_summaries` (
  `product_id` bigint(20) unsigned NOT NULL,
  `review_count` int(10) unsigned NOT NULL DEFAULT 0,
  `rating_avg` decimal(3,2) NOT NULL DEFAULT 0.00,
  `refreshed_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_rating_summaries_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `product_variants`;
CREATE TABLE `product_variants` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `product_id` bigint(20) unsigned NOT NULL,
  `size` varchar(8) NOT NULL,
  `color` varchar(60) NOT NULL DEFAULT '',
  `color_hex` char(7) NOT NULL DEFAULT '#000000',
  `material` varchar(120) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Active',
  `max_per_order` tinyint(3) unsigned NOT NULL DEFAULT 3,
  `position` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  `live_key` varchar(64) GENERATED ALWAYS AS (if(`deleted_at` is null,concat(`product_id`,'|',`size`),NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_variants_sku` (`public_id`),
  UNIQUE KEY `uq_variants_live_size` (`live_key`),
  KEY `fk_variants_product` (`product_id`),
  CONSTRAINT `fk_variants_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_variants_status` CHECK (`status` in ('Active','Low','Out','Archived'))
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(80) NOT NULL,
  `name` varchar(160) NOT NULL,
  `category` varchar(80) NOT NULL DEFAULT '',
  `category_id` bigint(20) unsigned DEFAULT NULL,
  `item_ref` varchar(40) DEFAULT NULL,
  `sku_code` varchar(8) NOT NULL DEFAULT '',
  `listing_size` varchar(8) NOT NULL DEFAULT '',
  `description` text DEFAULT NULL,
  `story` text DEFAULT NULL,
  `fabric` varchar(255) NOT NULL DEFAULT '',
  `care` varchar(255) NOT NULL DEFAULT '',
  `price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `compare_at_price` decimal(12,2) DEFAULT NULL,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `color` varchar(60) NOT NULL DEFAULT '',
  `badge` varchar(40) DEFAULT NULL,
  `image_position` varchar(16) NOT NULL DEFAULT 'top-left',
  `audience` varchar(16) NOT NULL DEFAULT 'unisex',
  `collection_slug` varchar(80) NOT NULL DEFAULT '',
  `is_new` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(16) NOT NULL DEFAULT 'Draft',
  `tax_note` varchar(120) DEFAULT NULL,
  `position` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_products_slug` (`public_id`),
  KEY `ix_products_status` (`status`,`deleted_at`),
  KEY `ix_products_audience` (`audience`),
  KEY `ix_products_collection` (`collection_slug`),
  KEY `ix_products_item_ref` (`item_ref`),
  KEY `ix_products_sku_code` (`sku_code`),
  KEY `fk_products_category` (`category_id`),
  CONSTRAINT `fk_products_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_products_item_ref` FOREIGN KEY (`item_ref`) REFERENCES `stock_items` (`public_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `ck_products_image_position` CHECK (`image_position` in ('top-left','top-right','bottom-left','bottom-right')),
  CONSTRAINT `ck_products_audience` CHECK (`audience` in ('men','women','unisex')),
  CONSTRAINT `ck_products_status` CHECK (`status` in ('Published','Scheduled','Draft'))
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `refunds`;
CREATE TABLE `refunds` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `payment_id` bigint(20) unsigned NOT NULL,
  `order_number` varchar(40) NOT NULL DEFAULT '',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `reason` varchar(40) NOT NULL DEFAULT 'Goodwill',
  `status` varchar(16) NOT NULL DEFAULT 'Requested',
  `gateway_refund_id` varchar(120) DEFAULT NULL,
  `requested_by` bigint(20) unsigned DEFAULT NULL,
  `approved_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_refunds_public_id` (`public_id`),
  KEY `ix_refunds_payment` (`payment_id`),
  KEY `ix_refunds_status` (`status`),
  KEY `fk_refunds_requested_by` (`requested_by`),
  KEY `fk_refunds_approved_by` (`approved_by`),
  CONSTRAINT `fk_refunds_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_refunds_payment` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_refunds_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_refunds_status` CHECK (`status` in ('Requested','Processing','Succeeded','Failed'))
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `return_requests`;
CREATE TABLE `return_requests` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `order_number` varchar(40) NOT NULL DEFAULT '',
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `customer_name` varchar(120) NOT NULL DEFAULT '',
  `item_label` varchar(160) NOT NULL DEFAULT '',
  `order_item_id` bigint(20) unsigned DEFAULT NULL,
  `reason` varchar(40) NOT NULL,
  `outcome` varchar(16) NOT NULL DEFAULT 'Voucher',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'INR',
  `replacement_product_id` bigint(20) unsigned DEFAULT NULL,
  `replacement_label` varchar(160) NOT NULL DEFAULT '',
  `state` varchar(24) NOT NULL DEFAULT 'New',
  `customer_status` varchar(32) NOT NULL DEFAULT 'Pickup scheduled',
  `destination` varchar(120) NOT NULL DEFAULT '',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `pickup_slot` varchar(80) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_return_requests_public_id` (`public_id`),
  KEY `ix_return_requests_state` (`state`),
  KEY `ix_return_requests_user` (`user_id`,`created_at`),
  KEY `ix_return_requests_order` (`order_number`),
  KEY `fk_return_requests_order_item` (`order_item_id`),
  KEY `fk_return_requests_replacement` (`replacement_product_id`),
  CONSTRAINT `fk_return_requests_order_item` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_return_requests_replacement` FOREIGN KEY (`replacement_product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_return_requests_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_return_requests_outcome` CHECK (`outcome` in ('Voucher','Exchange')),
  CONSTRAINT `ck_return_requests_state` CHECK (`state` in ('New','Awaiting payment','Approved','Completed','Rejected')),
  CONSTRAINT `ck_return_requests_customer_status` CHECK (`customer_status` in ('Pickup scheduled','Voucher issued','Exchange on its way'))
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `return_status_history`;
CREATE TABLE `return_status_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `return_id` bigint(20) unsigned NOT NULL,
  `from_state` varchar(24) NOT NULL DEFAULT '',
  `to_state` varchar(24) NOT NULL,
  `actor_id` bigint(20) unsigned DEFAULT NULL,
  `note` varchar(255) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_return_status_history_return` (`return_id`,`created_at`),
  KEY `fk_return_status_history_actor` (`actor_id`),
  CONSTRAINT `fk_return_status_history_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_return_status_history_return` FOREIGN KEY (`return_id`) REFERENCES `return_requests` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `review_moderation_history`;
CREATE TABLE `review_moderation_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `review_id` bigint(20) unsigned NOT NULL,
  `from_status` varchar(16) NOT NULL DEFAULT '',
  `to_status` varchar(16) NOT NULL,
  `actor_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_review_moderation_review` (`review_id`,`created_at`),
  KEY `fk_review_moderation_actor` (`actor_id`),
  CONSTRAINT `fk_review_moderation_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_review_moderation_review` FOREIGN KEY (`review_id`) REFERENCES `reviews` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `reviews`;
CREATE TABLE `reviews` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `product_name` varchar(160) NOT NULL DEFAULT '',
  `product_id` bigint(20) unsigned DEFAULT NULL,
  `rating` tinyint(3) unsigned NOT NULL,
  `customer_name` varchar(120) NOT NULL DEFAULT '',
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `headline` varchar(160) NOT NULL DEFAULT '',
  `body` text DEFAULT NULL,
  `fit` varchar(40) DEFAULT NULL,
  `submitted_label` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Pending',
  `origin` varchar(16) NOT NULL DEFAULT 'Customer',
  `order_number` varchar(40) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `order_product_key` varchar(120) GENERATED ALWAYS AS (if(`order_number` is not null and `product_id` is not null,concat(`order_number`,'#',`product_id`),NULL)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_reviews_public_id` (`public_id`),
  UNIQUE KEY `uq_reviews_order_product` (`order_product_key`),
  KEY `ix_reviews_status` (`status`,`created_at`),
  KEY `ix_reviews_product` (`product_id`,`status`),
  KEY `fk_reviews_user` (`user_id`),
  CONSTRAINT `fk_reviews_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_reviews_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_reviews_rating` CHECK (`rating` between 1 and 5),
  CONSTRAINT `ck_reviews_status` CHECK (`status` in ('Pending','Approved','Rejected')),
  CONSTRAINT `ck_reviews_origin` CHECK (`origin` in ('Customer','Console'))
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `role_permissions`;
CREATE TABLE `role_permissions` (
  `role_id` int(10) unsigned NOT NULL,
  `permission_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `ix_role_permissions_permission` (`permission_id`),
  CONSTRAINT `fk_role_permissions_permission` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_role_permissions_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(32) NOT NULL,
  `is_system` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_roles_code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `schema_migrations`;
CREATE TABLE `schema_migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `filename` varchar(191) NOT NULL,
  `checksum` char(64) NOT NULL,
  `statements` int(10) unsigned NOT NULL DEFAULT 0,
  `applied_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_schema_migrations_filename` (`filename`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `search_queries`;
CREATE TABLE `search_queries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `q` varchar(190) NOT NULL,
  `results` int(10) unsigned NOT NULL DEFAULT 0,
  `session_kind` varchar(16) NOT NULL DEFAULT 'guest',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_search_queries_q` (`q`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `shipment_events`;
CREATE TABLE `shipment_events` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `shipment_id` bigint(20) unsigned NOT NULL,
  `label` varchar(80) NOT NULL,
  `detail` varchar(255) NOT NULL DEFAULT '',
  `time_label` varchar(40) NOT NULL DEFAULT '',
  `is_complete` tinyint(1) NOT NULL DEFAULT 0,
  `position` int(11) NOT NULL DEFAULT 0,
  `source` varchar(16) NOT NULL DEFAULT 'internal',
  `external_ref` varchar(120) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_shipment_events_shipment` (`shipment_id`,`position`),
  CONSTRAINT `fk_shipment_events_shipment` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_shipment_events_source` CHECK (`source` in ('internal','external'))
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `shipment_labels`;
CREATE TABLE `shipment_labels` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `shipment_id` bigint(20) unsigned NOT NULL,
  `media_id` bigint(20) unsigned DEFAULT NULL,
  `printed_count` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_shipment_labels_shipment` (`shipment_id`),
  KEY `fk_shipment_labels_media` (`media_id`),
  CONSTRAINT `fk_shipment_labels_media` FOREIGN KEY (`media_id`) REFERENCES `media_assets` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_shipment_labels_shipment` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `shipments`;
CREATE TABLE `shipments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `order_id` bigint(20) unsigned NOT NULL,
  `order_number` varchar(40) NOT NULL DEFAULT '',
  `provider` varchar(40) NOT NULL DEFAULT '',
  `awb` varchar(60) NOT NULL DEFAULT '',
  `destination` varchar(120) NOT NULL DEFAULT '',
  `dispatched_label` varchar(40) NOT NULL DEFAULT '',
  `promise_label` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Dispatched',
  `fail_reason` varchar(120) DEFAULT NULL,
  `handling` varchar(24) DEFAULT NULL,
  `tracking_token` varchar(40) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_shipments_public_id` (`public_id`),
  UNIQUE KEY `uq_shipments_token` (`tracking_token`),
  KEY `ix_shipments_order` (`order_id`),
  KEY `ix_shipments_status` (`status`),
  CONSTRAINT `fk_shipments_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_shipments_status` CHECK (`status` in ('Dispatched','In transit','Delivered','Failed','Cancelled'))
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `staff_activity_logs`;
CREATE TABLE `staff_activity_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `staff_user_id` bigint(20) unsigned NOT NULL,
  `action` varchar(120) NOT NULL,
  `resource` varchar(120) NOT NULL DEFAULT '',
  `result` varchar(16) NOT NULL DEFAULT 'Completed',
  `where_label` varchar(80) NOT NULL DEFAULT '',
  `request_id` varchar(64) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_staff_activity_user` (`staff_user_id`,`created_at`),
  CONSTRAINT `fk_staff_activity_user` FOREIGN KEY (`staff_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_staff_activity_result` CHECK (`result` in ('Completed','Denied','Recorded'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `stock_items`;
CREATE TABLE `stock_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `item_name` varchar(160) NOT NULL,
  `category` varchar(16) NOT NULL DEFAULT 'Top',
  `item_type` varchar(80) NOT NULL DEFAULT '',
  `sizes_csv` varchar(120) NOT NULL DEFAULT '',
  `image_media_id` bigint(20) unsigned DEFAULT NULL,
  `warehouse_id` bigint(20) unsigned NOT NULL,
  `total_units` int(10) unsigned NOT NULL DEFAULT 0,
  `reserved_units` int(10) unsigned NOT NULL DEFAULT 0,
  `version` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_stock_items_public_id` (`public_id`),
  KEY `ix_stock_items_warehouse` (`warehouse_id`),
  KEY `fk_stock_items_image` (`image_media_id`),
  CONSTRAINT `fk_stock_items_image` FOREIGN KEY (`image_media_id`) REFERENCES `media_assets` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_stock_items_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`),
  CONSTRAINT `ck_stock_items_reserved` CHECK (`reserved_units` <= `total_units`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `store_settings`;
CREATE TABLE `store_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(120) NOT NULL,
  `value_json` mediumtext DEFAULT NULL,
  `version` int(10) unsigned NOT NULL DEFAULT 1,
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_store_settings_key` (`key`),
  KEY `fk_store_settings_actor` (`updated_by`),
  CONSTRAINT `fk_store_settings_actor` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `support_queries`;
CREATE TABLE `support_queries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `customer_name` varchar(120) NOT NULL DEFAULT '',
  `email` varchar(190) NOT NULL DEFAULT '',
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `topic` varchar(40) NOT NULL,
  `order_number` varchar(40) NOT NULL DEFAULT 'No order',
  `message` text NOT NULL,
  `sent_label` varchar(60) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Open',
  `reply` text NOT NULL,
  `resolved_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_support_queries_public_id` (`public_id`),
  KEY `ix_support_queries_status` (`status`,`created_at`),
  KEY `ix_support_queries_user` (`user_id`),
  KEY `fk_support_queries_resolver` (`resolved_by`),
  CONSTRAINT `fk_support_queries_resolver` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_support_queries_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_support_queries_status` CHECK (`status` in ('Open','Resolved'))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `support_status_history`;
CREATE TABLE `support_status_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `query_id` bigint(20) unsigned NOT NULL,
  `from_status` varchar(16) NOT NULL DEFAULT '',
  `to_status` varchar(16) NOT NULL,
  `actor_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `ix_support_status_history_query` (`query_id`,`created_at`),
  KEY `fk_support_status_history_actor` (`actor_id`),
  CONSTRAINT `fk_support_status_history_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_support_status_history_query` FOREIGN KEY (`query_id`) REFERENCES `support_queries` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `trading_days`;
CREATE TABLE `trading_days` (
  `day` date NOT NULL,
  `revenue` decimal(14,2) NOT NULL DEFAULT 0.00,
  `orders` int(10) unsigned NOT NULL DEFAULT 0,
  `sessions` int(10) unsigned NOT NULL DEFAULT 0,
  `returns` int(10) unsigned NOT NULL DEFAULT 0,
  `refreshed_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`day`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `user_addresses`;
CREATE TABLE `user_addresses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `label` varchar(40) NOT NULL DEFAULT '',
  `name` varchar(120) NOT NULL,
  `street` varchar(255) NOT NULL,
  `city` varchar(80) NOT NULL,
  `state` varchar(80) NOT NULL,
  `pincode` char(6) NOT NULL,
  `phone` varchar(20) NOT NULL DEFAULT '',
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `position` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_addresses_public_id` (`public_id`),
  KEY `ix_addresses_user` (`user_id`,`deleted_at`),
  CONSTRAINT `fk_addresses_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `user_roles`;
CREATE TABLE `user_roles` (
  `user_id` bigint(20) unsigned NOT NULL,
  `role_id` int(10) unsigned NOT NULL,
  `granted_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `ix_user_roles_role` (`role_id`),
  KEY `fk_user_roles_granted_by` (`granted_by`),
  CONSTRAINT `fk_user_roles_granted_by` FOREIGN KEY (`granted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_user_roles_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_roles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `user_sessions`;
CREATE TABLE `user_sessions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `audience` varchar(16) NOT NULL,
  `token_hash` binary(32) NOT NULL,
  `ip` varbinary(16) DEFAULT NULL,
  `user_agent` varchar(255) NOT NULL DEFAULT '',
  `last_active_at` datetime(6) NOT NULL,
  `idle_expires_at` datetime(6) DEFAULT NULL,
  `absolute_expires_at` datetime(6) DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sessions_token` (`token_hash`),
  KEY `ix_sessions_user` (`user_id`,`audience`,`revoked_at`),
  CONSTRAINT `fk_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_sessions_audience` CHECK (`audience` in ('customer','staff'))
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(40) NOT NULL,
  `type` varchar(16) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'ACTIVE',
  `name` varchar(120) NOT NULL,
  `email` varchar(190) NOT NULL,
  `email_normalized` varchar(190) NOT NULL,
  `phone` varchar(20) NOT NULL DEFAULT '',
  `password_hash` varchar(255) NOT NULL DEFAULT '',
  `photo_media_id` bigint(20) unsigned DEFAULT NULL,
  `last_seen_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_public_id` (`public_id`),
  UNIQUE KEY `uq_users_email_per_type` (`type`,`email_normalized`),
  KEY `ix_users_status` (`status`),
  KEY `ix_users_last_seen` (`last_seen_at`),
  KEY `fk_users_photo` (`photo_media_id`),
  CONSTRAINT `fk_users_photo` FOREIGN KEY (`photo_media_id`) REFERENCES `media_assets` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_users_type` CHECK (`type` in ('CUSTOMER','STAFF')),
  CONSTRAINT `ck_users_status` CHECK (`status` in ('ACTIVE','BLOCKED'))
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `variant_inventory`;
CREATE TABLE `variant_inventory` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `variant_id` bigint(20) unsigned NOT NULL,
  `stock_item_id` bigint(20) unsigned DEFAULT NULL,
  `on_hand` int(11) NOT NULL DEFAULT 0,
  `reserved` int(11) NOT NULL DEFAULT 0,
  `available` int(11) GENERATED ALWAYS AS (`on_hand` - `reserved`) STORED,
  `low_at` tinyint(3) unsigned NOT NULL DEFAULT 4,
  `version` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_variant_inventory_variant` (`variant_id`),
  KEY `ix_variant_inventory_stock_item` (`stock_item_id`),
  KEY `ix_variant_inventory_available` (`available`),
  CONSTRAINT `fk_variant_inventory_stock_item` FOREIGN KEY (`stock_item_id`) REFERENCES `stock_items` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_variant_inventory_variant` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ck_variant_inventory_reserved` CHECK (`reserved` >= 0 and `reserved` <= `on_hand`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `vouchers`;
CREATE TABLE `vouchers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(40) NOT NULL,
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `return_public_id` varchar(40) NOT NULL DEFAULT '',
  `reason` varchar(160) NOT NULL DEFAULT '',
  `customer_name` varchar(120) NOT NULL DEFAULT '',
  `customer_user_id` bigint(20) unsigned DEFAULT NULL,
  `issued_on` date NOT NULL,
  `expires_on` date NOT NULL,
  `claimed_on` date DEFAULT NULL,
  `claimed_order` varchar(40) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `return_key` varchar(40) GENERATED ALWAYS AS (nullif(`return_public_id`,'')) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_vouchers_code` (`code`),
  UNIQUE KEY `uq_vouchers_return` (`return_key`),
  KEY `ix_vouchers_customer` (`customer_user_id`,`claimed_on`),
  CONSTRAINT `fk_vouchers_customer` FOREIGN KEY (`customer_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ck_vouchers_window` CHECK (`expires_on` > `issued_on`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `warehouses`;
CREATE TABLE `warehouses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `public_id` varchar(16) NOT NULL,
  `name` varchar(120) NOT NULL,
  `available_label` varchar(40) NOT NULL DEFAULT '',
  `capacity_pct` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `cutoff` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL DEFAULT 'Online',
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_warehouses_public_id` (`public_id`),
  CONSTRAINT `ck_warehouses_status` CHECK (`status` in ('Online','Draft','Disabled'))
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `webhook_inbox`;
CREATE TABLE `webhook_inbox` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `provider` varchar(40) NOT NULL,
  `event_id` varchar(190) NOT NULL,
  `signature_ok` tinyint(1) NOT NULL DEFAULT 0,
  `payload` mediumtext DEFAULT NULL,
  `processed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_webhook_inbox_event` (`provider`,`event_id`),
  KEY `ix_webhook_inbox_unprocessed` (`processed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP VIEW IF EXISTS `v_order_timeline`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v_order_timeline` AS select `o`.`id` AS `order_id`,`o`.`number` AS `order_number`,`h`.`created_at` AS `at`,`h`.`to_status` AS `label`,`h`.`note` AS `detail`,`h`.`actor_type` AS `actor` from (`orders` `o` join `order_status_history` `h` on(`h`.`order_id` = `o`.`id`)) union all select `o`.`id` AS `order_id`,`o`.`number` AS `order_number`,`e`.`created_at` AS `at`,`e`.`label` AS `label`,`e`.`detail` AS `detail`,'system' AS `actor` from ((`orders` `o` join `shipments` `s` on(`s`.`order_id` = `o`.`id`)) join `shipment_events` `e` on(`e`.`shipment_id` = `s`.`id`));

DROP VIEW IF EXISTS `v_variant_availability`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v_variant_availability` AS select `p`.`public_id` AS `product_slug`,`v`.`public_id` AS `sku`,`v`.`id` AS `variant_id`,`v`.`size` AS `size`,`v`.`color` AS `color`,`v`.`color_hex` AS `color_hex`,`v`.`material` AS `material`,coalesce(`vi`.`available`,0) AS `available`,case when coalesce(`vi`.`available`,0) <= 0 then 'SOLD_OUT' when coalesce(`vi`.`available`,0) < coalesce(`vi`.`low_at`,4) then 'LOW_STOCK' else 'IN_STOCK' end AS `stock` from ((`product_variants` `v` join `products` `p` on(`p`.`id` = `v`.`product_id`)) left join `variant_inventory` `vi` on(`vi`.`variant_id` = `v`.`id`)) where `v`.`deleted_at` is null and `p`.`deleted_at` is null;

DROP VIEW IF EXISTS `v_dashboard_queues`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v_dashboard_queues` AS select (select count(0) from `orders` where `orders`.`console_state` = 'Placed') AS `orders_to_confirm`,(select count(0) from `payments` where `payments`.`status` = 'Failed') AS `payment_exceptions`,(select count(0) from `orders` `o` where `o`.`console_state` = 'Confirmed' and !exists(select 1 from `shipments` `s` where `s`.`order_id` = `o`.`id` and `s`.`status` not in ('Failed','Cancelled') limit 1)) AS `ready_to_dispatch`,(select count(0) from `return_requests` where `return_requests`.`state` = 'New') AS `returns_to_review`,(select count(0) from `v_variant_availability` where `v_variant_availability`.`stock` in ('LOW_STOCK','SOLD_OUT')) AS `stock_at_risk`,(select count(0) from `support_queries` where `support_queries`.`status` = 'Open') AS `open_tickets`;

SET FOREIGN_KEY_CHECKS = 1;

-- Reference data: RBAC matrix and store settings.
-- Demo accounts are NOT here — run `php bin/console.php seed`.

SET FOREIGN_KEY_CHECKS = 0;

-- schema_migrations (14 rows)
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (1, '0001_platform_identity.sql', 'afbd2a7ffd802fc5f0ac0c56f84430e07ecb27e871a3e2c078d6bed5fd45528e', 11, '2026-08-17 07:34:30.859624');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (2, '0002_catalog.sql', '5bb261f08185d986c282290c398571acc09779bed3da20b128169c625d856050', 8, '2026-08-17 07:34:30.958934');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (3, '0003_inventory.sql', 'a09060a2cf126ab975e482bcb561d5cfc500f6baadce0e2fa85e6d81bd6d6c1c', 8, '2026-08-17 07:34:31.096824');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (4, '0004_cart_coupons_vouchers.sql', '16c3d1e04b08b57903bd689bff97b8b68e2a0f9cdfe7bb4820862ae38ca3a50e', 6, '2026-08-17 07:34:31.162905');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (5, '0005_orders_payments.sql', '96e321780b744fc9e3e7e9506a3b371dc88ba9bb230a6e8759110f713a7ea5ba', 12, '2026-08-17 07:34:31.387304');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (6, '0006_shipping_tracking.sql', '4791f7a80c3aaa6553dccfd06dff7cf259213fdeeb04ab0c5058d74647f54127', 5, '2026-08-17 07:34:31.452180');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (7, '0007_returns_reviews_support.sql', '09ddb5756cbb20390060db0760e2e4c38843e1fa8df1b0e4ebdcea7f8e2186b2', 7, '2026-08-17 07:34:31.552679');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (8, '0008_cms_settings_platform.sql', '472522f08112fa51e0e0fa9aefc1129e34fd72e9f7beec66145a15eade902eea', 11, '2026-08-17 07:34:31.702321');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (9, '0009_analytics_dashboard.sql', '7196bc239f873acf88ce2802207c8d5e5f8c9f72f119e0d9b6afbb4fe2c56f10', 3, '2026-08-17 07:34:31.740745');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (10, '0010_views.sql', '590bede9a4b3a60d70694066f6eb5d1810a640a7ee176efe28ebf078ebc220a8', 3, '2026-08-17 07:34:31.764209');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (11, '0011_catalog_console_fields.sql', '7e1ab64d473f3fde014d59e3563bbeba66c708c574f5615ccbb07b8b43311b74', 2, '2026-08-17 07:34:31.816513');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (12, '0012_orders_optional_account.sql', '5f2bac4ab5aaafa05d5ad499484f62bab6a16b7cb9e145d8fa1e2298ef4eb1a9', 3, '2026-08-17 07:34:31.877742');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (13, '0013_vocabularies_out_of_the_schema.sql', '2ab5a5d73eb51b098b0cbd6cf55c879bb66812aa14a31c991094dcb1b7c4a107', 6, '2026-08-17 07:34:31.896345');
INSERT INTO `schema_migrations` (`id`, `filename`, `checksum`, `statements`, `applied_at`) VALUES (14, '0014_item_photos.sql', '69eb924f84309ac6ef7a13990f8d00b682738b24738997c80dce96c54e466707', 4, '2026-08-17 07:34:31.960549');

-- roles (4 rows)
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (1, 'ADMIN', 1);
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (2, 'MANAGER', 1);
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (3, 'SUPPORT', 1);
INSERT INTO `roles` (`id`, `code`, `is_system`) VALUES (4, 'WAREHOUSE', 1);

-- permissions (28 rows)
INSERT INTO `permissions` (`id`, `code`) VALUES (28, '*');
INSERT INTO `permissions` (`id`, `code`) VALUES (26, 'audit.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (7, 'catalog.edit');
INSERT INTO `permissions` (`id`, `code`) VALUES (8, 'catalog.publish');
INSERT INTO `permissions` (`id`, `code`) VALUES (6, 'catalog.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (14, 'coupons.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (21, 'customers.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (20, 'customers.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (1, 'dashboard.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (10, 'inventory.adjust');
INSERT INTO `permissions` (`id`, `code`) VALUES (11, 'inventory.transfer');
INSERT INTO `permissions` (`id`, `code`) VALUES (9, 'inventory.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (27, 'media.upload');
INSERT INTO `permissions` (`id`, `code`) VALUES (3, 'orders.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (2, 'orders.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (17, 'payments.exports.create');
INSERT INTO `permissions` (`id`, `code`) VALUES (16, 'payments.reconcile');
INSERT INTO `permissions` (`id`, `code`) VALUES (15, 'payments.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (19, 'refunds.approve');
INSERT INTO `permissions` (`id`, `code`) VALUES (18, 'refunds.request');
INSERT INTO `permissions` (`id`, `code`) VALUES (24, 'reports.operational.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (13, 'returns.approve');
INSERT INTO `permissions` (`id`, `code`) VALUES (12, 'returns.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (22, 'reviews.moderate');
INSERT INTO `permissions` (`id`, `code`) VALUES (25, 'settings.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (5, 'shipping.manage');
INSERT INTO `permissions` (`id`, `code`) VALUES (4, 'shipping.view');
INSERT INTO `permissions` (`id`, `code`) VALUES (23, 'support.tickets.manage');

-- role_permissions (40 rows)
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (1, 28);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 1);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 2);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 3);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 4);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 5);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 6);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 7);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 8);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 9);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 10);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 11);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 12);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 13);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 14);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 15);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 16);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 18);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 20);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 21);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 22);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 23);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 24);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (2, 27);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 1);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 2);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 4);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 12);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 15);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 20);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 22);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (3, 23);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 1);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 2);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 4);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 5);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 9);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 10);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 11);
INSERT INTO `role_permissions` (`role_id`, `permission_id`) VALUES (4, 12);

-- store_settings (15 rows)
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (1, 'delivery', '{\"standard_fee\":199,\"express_fee\":499,\"free_over\":4999,\"standard_window\":[3,5],\"express_window\":[1,2]}', 1, NULL, '2026-08-17 07:34:31.983762');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (2, 'cod', '{\"max\":5000,\"fee\":0,\"waive_over\":null}', 1, NULL, '2026-08-17 07:34:31.984083');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (3, 'inventory', '{\"low_stock_at\":4,\"reservation_ttl_prepaid\":900,\"reservation_ttl_cod\":600,\"max_per_order\":3,\"categories\":[\"Top\",\"Bottom\"],\"sizes_by_category\":{\"Top\":[\"S\",\"M\",\"L\",\"XL\",\"XXL\"],\"Bottom\":[\"30\",\"32\",\"34\",\"36\",\"38\",\"40\",\"42\"]},\"types_by_category\":{\"Top\":[\"T-shirt\",\"Shirt\",\"Hoodie\",\"Overshirt\",\"Jacket\"],\"Bottom\":[\"Jeans\",\"Cargo\",\"Casual\",\"Joggers\",\"Shorts\"]}}', 1, NULL, '2026-08-17 07:34:31.984458');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (4, 'shipping', '{\"providers\":[\"Blue Dart\",\"Delhivery\",\"Ecom Express\"],\"fail_reasons\":[\"Nobody was home\",\"Address was wrong\",\"Customer said no\",\"Could not reach the customer\",\"Not shared yet\"],\"max_delivery_attempts\":3,\"handling_states\":[\"Needs action\",\"Sending back\",\"Back in store\"]}', 1, NULL, '2026-08-17 07:34:31.986211');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (5, 'returns', '{\"reasons\":[\"Size / fit\",\"Changed mind\",\"Quality concern\",\"Wrong item\",\"Damaged in transit\"],\"outcomes\":[\"Voucher\",\"Exchange\"],\"window_days\":14}', 1, NULL, '2026-08-17 07:34:31.986607');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (6, 'payments', '{\"gateways\":[\"Razorpay\",\"Stripe\",\"Cashfree\",\"On device\",\"Courier\"],\"refund_reasons\":[\"Return approved\",\"Order cancelled\",\"Payment mismatch\",\"Goodwill\"],\"methods\":[\"UPI\",\"Card\",\"Netbanking\",\"Cash on delivery\"]}', 1, NULL, '2026-08-17 07:34:31.987005');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (7, 'catalog', '{\"product_states\":[\"Published\",\"Scheduled\",\"Draft\"],\"collection_states\":[\"Live\",\"Scheduled\",\"Draft\"],\"variant_states\":[\"Active\",\"Low\",\"Out\",\"Archived\"]}', 1, NULL, '2026-08-17 07:34:31.987268');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (8, 'media', '{\"max_bytes_console\":8388608,\"max_bytes_customer\":5242880,\"max_bytes_staff_photo\":2097152,\"allowed_mime\":[\"image/jpeg\",\"image/png\",\"image/webp\"],\"max_edge\":1600,\"quality\":82}', 1, NULL, '2026-08-17 07:34:31.987514');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (9, 'security', '{\"login_lockout_after\":20,\"login_lockout_window\":900,\"idempotency_ttl_hours\":48}', 1, NULL, '2026-08-17 07:34:31.987756');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (10, 'sessions', '{\"customer_ttl\":2592000,\"staff_idle_ttl\":900}', 1, NULL, '2026-08-17 07:34:31.988004');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (11, 'id_pools', '{\"order\":{\"prefix\":\"ord-local-\",\"width\":2,\"from\":1,\"to\":30},\"tracking\":{\"prefix\":\"track-local-\",\"width\":2,\"from\":1,\"to\":30},\"payment\":{\"prefix\":\"pay_ICE\",\"width\":4,\"from\":2001,\"to\":2030},\"customer\":{\"prefix\":\"cus-\",\"width\":4,\"from\":2050,\"to\":2079}}', 1, NULL, '2026-08-17 07:34:31.988258');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (12, 'id_series', '{\"shipment\":{\"prefix\":\"shp-\",\"width\":0,\"from\":1051},\"pickup\":{\"prefix\":\"PICK-\",\"width\":4,\"from\":413},\"review\":{\"prefix\":\"REV-\",\"width\":0,\"from\":2001},\"support\":{\"prefix\":\"IO-Q-\",\"width\":0,\"from\":1004},\"return\":{\"prefix\":\"ret-\",\"width\":3,\"from\":1},\"refund\":{\"prefix\":\"ref_ICE\",\"width\":3,\"from\":1},\"stock_item\":{\"prefix\":\"ITM-\",\"width\":3,\"from\":1},\"transfer\":{\"prefix\":\"TRF-\",\"width\":3,\"from\":1},\"voucher\":{\"prefix\":\"IOV\",\"width\":3,\"from\":1}}', 1, NULL, '2026-08-17 07:34:31.988524');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (13, 'order_number', '{\"prefix\":\"IO-2026-\",\"next_serial\":1049}', 1, NULL, '2026-08-17 07:34:31.988800');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (14, 'support', '{\"topics\":[\"Delivery\",\"Return or exchange\",\"Payment or refund\",\"Product and fit\",\"Something else\"],\"no_order_label\":\"No order\",\"slas\":{\"first_response_hours\":24,\"resolution_hours\":72}}', 1, NULL, '2026-08-17 07:34:31.989053');
INSERT INTO `store_settings` (`id`, `key`, `value_json`, `version`, `updated_by`, `updated_at`) VALUES (15, 'business', '{\"name\":\"Iced_out\",\"support_email\":\"help@iced-out.example\",\"gstin\":\"\",\"tax_rates\":[]}', 1, NULL, '2026-08-17 07:34:31.989423');

SET FOREIGN_KEY_CHECKS = 1;
