"use client";

import { AlertTriangle, Check, Image as ImageIcon, Save, Upload } from "lucide-react";
import { useState } from "react";

const steps = ["Details", "Variants", "Media", "Pricing", "Inventory", "Shipping", "SEO", "Size chart"];

export function AdminProductEditor({ productId }: { productId: string }) {
  const [step, setStep] = useState("Details");
  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Catalog / Product editor</p><h1>{productId === "afterdark-hoodie" ? "Afterdark Hoodie" : productId.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ")}</h1><span>Draft changes stay independent from publish eligibility.</span></div><div className="admin-heading-actions"><button type="button"><Save size={15} /> Save draft</button><button className="admin-primary" type="button">Run publish checks</button></div></div><div className="product-editor-stepper" role="tablist" aria-label="Product editor steps">{steps.map((item, index) => <button className={step === item ? "is-active" : ""} onClick={() => setStep(item)} type="button" role="tab" aria-selected={step === item} key={item}><span>{index < 2 ? <Check size={12} /> : index + 1}</span>{item}</button>)}</div><div className="product-editor-layout"><main><section><p className="eyebrow">Current step / {step}</p><h2>{step === "Details" ? "Define the product truth." : `${step} configuration`}</h2><p>Fields shown here are typed frontend previews. Server validation remains mandatory before save and publication.</p></section>{step === "Details" ? <div className="product-editor-fields"><label>Product name<input defaultValue="Afterdark Hoodie" /></label><label>Slug<input defaultValue="afterdark-hoodie" /></label><label>Collection<select defaultValue="Drop 001"><option>Drop 001</option><option>After Hours</option><option>Core Uniform</option></select></label><label>Category<select defaultValue="Outerwear"><option>Outerwear</option><option>Essentials</option><option>Bottoms</option></select></label><label className="is-wide">Short description<textarea rows={4} defaultValue="A dense, garment-washed hoodie cut with a dropped shoulder and deliberate weight." /></label></div> : <div className="product-editor-placeholder"><ImageIcon size={28} /><h3>{step} workspace</h3><p>The production surface will load its typed editor only when this step is selected.</p><button type="button"><Upload size={15} /> Add {step.toLowerCase()} data</button></div>}</main><aside><div className="publish-score"><strong>88%</strong><span>Publish readiness</span></div><div className="publish-checks"><span><Check size={14} /> Details complete</span><span><Check size={14} /> 5 unique SKUs</span><span><AlertTriangle size={14} /> 1 media alt text missing</span><span><AlertTriangle size={14} /> Size chart not linked</span></div><button type="button">Jump to first blocker</button><small>Archive replaces delete after the first order line exists.</small></aside></div></section>;
}
