"use client";

import { Barcode, Check, PackageCheck, ScanLine, TriangleAlert } from "lucide-react";
import { useState, type FormEvent } from "react";

export function FulfilmentWorkspace({ mode = "pick" }: { mode?: "allocation" | "pick" | "pack" | "dispatch" }) {
  const [scan, setScan] = useState("");
  const [feedback, setFeedback] = useState<"idle" | "success" | "error">("idle");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback(scan.toUpperCase() === "ADH-BLK-L" ? "success" : "error"); }
  return <section className="admin-workspace warehouse-workspace"><div className="admin-heading admin-heading--actions"><div><p>Warehouse / {mode}</p><h1>{mode === "pick" ? "Pick with certainty." : `${mode[0].toUpperCase()}${mode.slice(1)} queue`}</h1><span>Large targets, focused scanning, immediate evidence, and no silent quantity correction.</span></div><span className="warehouse-shift"><i className="status-dot" /> Shift active · BLR-01</span></div><div className="warehouse-wave"><div><span>Active wave</span><strong>WAVE-082</strong><small>12 orders · 32 units · Zone A</small></div><div><span>Current tote</span><strong>TOTE-14</strong><small>Order IO-2026-1048</small></div><div><span>Progress</span><strong>18 / 32</strong><small>56% complete</small></div><div><span>Cutoff</span><strong>17:30</strong><small>Blue Dart pickup</small></div></div><div className="warehouse-grid"><form className={`scanner-console is-${feedback}`} onSubmit={submit}><div><ScanLine size={34} /><p className="eyebrow">Scanner has focus</p><h2>Scan the next SKU.</h2><span>Expected: Afterdark Hoodie · Washed black · L</span></div><label><Barcode size={22} /><input autoFocus value={scan} onChange={(event) => { setScan(event.target.value); setFeedback("idle"); }} placeholder="Try ADH-BLK-L" aria-label="Scan SKU" /><button type="submit">Verify scan</button></label>{feedback === "success" && <div className="scan-feedback is-success"><Check size={20} /><p><strong>Correct SKU</strong><small>1 of 1 placed in TOTE-14</small></p></div>}{feedback === "error" && <div className="scan-feedback is-error"><TriangleAlert size={20} /><p><strong>Wrong SKU—do not pick</strong><small>Expected ADH-BLK-L. Rescan the correct variant.</small></p></div>}</form><aside className="pick-list"><header><PackageCheck size={19} /><div><span>Next locations</span><strong>Zone A / Rack 04</strong></div></header>{[{loc:"A-04-12",sku:"ADH-BLK-L",qty:"1"},{loc:"A-04-18",sku:"CHT-INK-M",qty:"1"},{loc:"A-06-02",sku:"BUO-BON-M",qty:"2"}].map((item, index) => <article className={index === 0 ? "is-current" : ""} key={item.sku}><span>{item.loc}</span><strong>{item.sku}</strong><b>× {item.qty}</b></article>)}</aside></div></section>;
}
