import { AlertTriangle, ArrowRight, Clock3, MapPin, PackageCheck, Route, Truck } from "lucide-react";
import Link from "next/link";

export const shipmentFixtures = [
  { id: "shp-1048", order: "IO-2026-1048", provider: "Blue Dart", awb: "••••1048", destination: "Bengaluru", state: "In transit", promise: "08–09 Aug" },
  { id: "shp-1046", order: "IO-2026-1046", provider: "Delhivery", awb: "••••4291", destination: "Delhi", state: "Ready", promise: "07 Aug" },
];

export function ShipmentWorkspace({ view = "active" }: { view?: "active" | "ndr" | "manifests" }) {
  if (view === "ndr") return <section className="admin-workspace"><div className="admin-heading"><p>Shipping / Non-delivery</p><h1>NDR recovery</h1><span>Reattempt, correct, reschedule, or return to origin with an explicit provider reason and customer evidence.</span></div><div className="admin-alert"><AlertTriangle size={20} /><div><strong>03 cases inside the recovery window</strong><p>Oldest case has 7 hours left before automatic RTO review.</p></div></div><div className="ndr-board">{[{id:"NDR-118",order:"IO-2026-1039",reason:"Customer unavailable",age:"17h",action:"Reschedule"},{id:"NDR-116",order:"IO-2026-1032",reason:"Incomplete landmark",age:"11h",action:"Correct address"},{id:"NDR-112",order:"IO-2026-1021",reason:"Refused at door",age:"5h",action:"Review RTO"}].map((item) => <article key={item.id}><Clock3 size={18} /><div><span>{item.id} · {item.age}</span><h2>{item.reason}</h2><p>{item.order} · customer contact remains masked</p></div><button type="button">{item.action}</button></article>)}</div></section>;
  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Shipping / {view}</p><h1>{view === "manifests" ? "Courier manifests" : "Active shipments"}</h1><span>Provider promises, AWB evidence, warehouse scope, and state drift in one operational view.</span></div><button className="admin-primary" type="button">{view === "manifests" ? "Close manifest" : "Generate AWB"}</button></div><div className="shipment-map"><div><Route size={25} /><span>BLR-01</span><i /><Truck size={25} /><span>Provider network</span><i /><MapPin size={25} /><span>Customer region</span></div><p>18 active · 02 delayed · 03 awaiting first scan</p></div><div className="shipment-records">{shipmentFixtures.map((item) => <article key={item.id}><PackageCheck size={19} /><div><span>{item.id} · AWB {item.awb}</span><h2>{item.order}</h2></div><p>{item.provider}<small>{item.destination}</small></p><p>{item.promise}<small>Current promise</small></p><span className="admin-status admin-status--processing">{item.state}</span><Link href={`/admin/shipments/${item.id}`}><ArrowRight size={16} /></Link></article>)}</div></section>;
}
