"use client";

import { BellRing, Check, CircleAlert, Clock3, Mail, MessageSquareText, Search, Send, ShieldCheck, Smartphone } from "lucide-react";
import { useState } from "react";

export type NotificationView = "templates" | "delivery-logs" | "preferences";

export function NotificationsWorkspace({ view }: { view: NotificationView }) {
  const [template, setTemplate] = useState("Order confirmed");
  if (view === "templates") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Notifications / Versioned templates</p><h1>Transactional clarity.</h1><span>Typed variables, channel-safe copy, locale fallbacks, previews, and test sends before publication.</span></div><button className="admin-primary" type="button">Create template</button></div><div className="template-studio"><aside>{["Order confirmed","Shipment dispatched","Return approved","Refund complete","Support reply"].map((item) => <button className={template === item ? "is-active" : ""} onClick={() => setTemplate(item)} type="button" key={item}><Mail size={15} /><span>{item}<small>en-IN · Published</small></span></button>)}</aside><main><header><div><p className="eyebrow">Email + SMS</p><h2>{template}</h2></div><span className="admin-status admin-status--captured">Published v8</span></header><label>Subject<input defaultValue={`${template} · {{order_number}}`} /></label><label>Preview text<input defaultValue="The latest verified state of your Iced_out order." /></label><label>Message body<textarea rows={8} defaultValue={`Hi {{customer_first_name}},\n\nYour order {{order_number}} has a verified update. Open the secure account timeline for current item, payment, and delivery facts.\n\nIced_out`} /></label><div className="template-tokens"><span>{"{{order_number}}"}</span><span>{"{{customer_first_name}}"}</span><span>{"{{secure_timeline_url}}"}</span></div><footer><button type="button">Preview all breakpoints</button><button type="button"><Send size={14} /> Prepare test send</button></footer></main><aside className="message-preview"><span>Iced_out / Email preview</span><BellRing size={25} /><h2>{template}</h2><p>The final channel output is rendered with allow-listed variables and production-safe URLs.</p><small><ShieldCheck size={13} /> No secret or raw provider payload can enter a template.</small></aside></div></section>;

  if (view === "delivery-logs") return <section className="admin-workspace"><div className="admin-heading"><p>Notifications / Delivery evidence</p><h1>Every message has a trail.</h1><span>Channel, consent class, provider reference, retries, failures, and final delivery status in a masked operational log.</span></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label="Search delivery logs" placeholder="Message, order, template, masked recipient" /></label><button type="button">Channel · All</button><button type="button">Status · All</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Message</th><th>Template / channel</th><th>Recipient</th><th>Reference</th><th>Status</th><th>Time</th></tr></thead><tbody>{[{id:"MSG-8842",template:"Shipment dispatched",channel:"Email",recipient:"aa•••@example.com",ref:"em_••••8842",status:"Delivered",time:"14:38"},{id:"MSG-8841",template:"OTP verification",channel:"SMS",recipient:"+91 ••••• 43210",ref:"sms_••••8841",status:"Delivered",time:"14:34"},{id:"MSG-8837",template:"Support reply",channel:"Email",recipient:"ri•••@example.com",ref:"em_••••8837",status:"Retrying",time:"14:18"}].map((item) => <tr key={item.id}><td><strong>{item.id}</strong></td><td>{item.template}<small>{item.channel}</small></td><td>{item.recipient}</td><td>{item.ref}</td><td><span className={`admin-status ${item.status === "Delivered" ? "admin-status--captured" : "admin-status--review"}`}>{item.status}</span></td><td>{item.time}</td></tr>)}</tbody></table></div><div className="admin-alert"><CircleAlert size={20} /><div><strong>Provider retry queue · 03</strong><p>Backoff is server-controlled; operators cannot force duplicate delivery.</p></div></div></section>;

  return <section className="admin-workspace"><div className="admin-heading"><p>Notifications / Channel policy</p><h1>Consent stays specific.</h1><span>Transactional necessity, marketing consent, customer preference, quiet hours, and provider health remain distinct controls.</span></div><div className="notification-policy-grid">{[{icon:Mail,name:"Email",health:"Healthy",transactional:true,marketing:true},{icon:Smartphone,name:"SMS",health:"Healthy",transactional:true,marketing:false},{icon:MessageSquareText,name:"WhatsApp",health:"Sandbox",transactional:false,marketing:false},{icon:BellRing,name:"Web push",health:"Preview",transactional:false,marketing:true}].map(({icon:Icon,name,health,transactional,marketing}) => <article key={name}><Icon size={22} /><div><span>{name}</span><strong>{health}</strong></div><label>Transactional<input type="checkbox" defaultChecked={transactional} /></label><label>Marketing<input type="checkbox" defaultChecked={marketing} /></label><small><Clock3 size={12} /> Quiet hours 21:00–08:00</small></article>)}</div><div className="admin-action-bar"><p><Check size={14} /> Required order and security messages never reuse optional marketing consent.</p><button type="button">Save preference preview</button></div></section>;
}
