"use client";

import { ArrowRight, BadgePercent, Check, Clock3, Eye, Gift, Heart, Megaphone, Search, ShoppingBag, Sparkles, Users } from "lucide-react";
import { useState } from "react";

export type MarketingView = "coupons" | "campaigns" | "abandoned-carts" | "recommendations";

export function MarketingWorkspace({ view }: { view: MarketingView }) {
  const [discount, setDiscount] = useState(15);
  const [strategy, setStrategy] = useState("Complete the uniform");

  if (view === "coupons") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Marketing / Eligibility rules</p><h1>Build a promise you can keep.</h1><span>Coupon language mirrors API rules and previews who qualifies, what changes, and why a cart may be excluded.</span></div><button className="admin-primary" type="button">Save draft coupon</button></div><div className="coupon-builder"><form><label>Code<input defaultValue="AFTERDARK15" /></label><label>Discount<input type="range" min="5" max="40" value={discount} onChange={(event) => setDiscount(Number(event.target.value))} /><strong>{discount}%</strong></label><label>Minimum merchandise value<input defaultValue="₹7,500" /></label><label>Applies to<select defaultValue="Drop 001"><option>Drop 001</option><option>Full-price catalog</option><option>Selected products</option></select></label><label>Customer eligibility<select defaultValue="First verified order"><option>First verified order</option><option>All verified customers</option><option>Selected segment</option></select></label><div className="coupon-conditions"><span><Check size={13} /> One use per customer</span><span><Check size={13} /> Excludes sale items</span><span><Check size={13} /> India primary store</span></div></form><aside><BadgePercent size={25} /><p className="eyebrow">Plain-language preview</p><h2>{discount}% off Drop 001.</h2><p>A verified customer placing their first order receives {discount}% off eligible full-price Drop 001 pieces when merchandise value reaches ₹7,500.</p><dl><div><dt>Example bag</dt><dd>₹17,800</dd></div><div><dt>Discount</dt><dd>−₹{Math.round(17800 * discount / 100).toLocaleString("en-IN")}</dd></div><div><dt>Result</dt><dd>Calculated again by API</dd></div></dl><small>No price is mutated by this frontend preview.</small></aside></div></section>;

  if (view === "campaigns") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Marketing / Campaign calendar</p><h1>Release with intent.</h1><span>Audience, creative, destination, consent, schedule, and measurement remain one reviewable campaign object.</span></div><button className="admin-primary" type="button"><Megaphone size={15} /> New campaign</button></div><div className="campaign-timeline"><span>04 Aug</span>{[{name:"Drop 001 / Last units",channel:"Email · Push",state:"Live",time:"Now → 06 Aug"},{name:"After Hours / Private access",channel:"Email",state:"Scheduled",time:"12 Aug · 19:30"},{name:"Core uniform / Editorial",channel:"Homepage · Email",state:"Draft",time:"Window unset"}].map((item, index) => <article key={item.name}><div><span>0{index + 1}</span><Megaphone size={19} /></div><p><small>{item.channel}</small><strong>{item.name}</strong><span>{item.time}</span></p><b className={`admin-status ${item.state === "Live" ? "admin-status--captured" : "admin-status--review"}`}>{item.state}</b><button type="button"><ArrowRight size={15} /></button></article>)}<span>12 Aug</span></div></section>;

  if (view === "abandoned-carts") return <section className="admin-workspace"><div className="admin-heading"><p>Marketing / Recovery</p><h1>Recover without pressure.</h1><span>Only consented, eligible sessions enter recovery; frequency caps and checkout state are rechecked before every send.</span></div><div className="admin-stat-grid"><article><span>Eligible carts</span><strong>184</strong><p>₹16.8L potential value</p></article><article><span>Recovered</span><strong>22.4%</strong><p>41 completed orders</p></article><article><span>Suppressed</span><strong>38</strong><p>No consent, ordered, or capped</p></article><article><span>Median recovery</span><strong>3h 18m</strong><p>After first reminder</p></article></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label="Search abandoned carts" placeholder="Masked customer, cart, product" /></label><button type="button">Segment · High intent</button></div><div className="recovery-cards">{[{customer:"A•••• K••••",bag:"Afterdark Hoodie · Core Heavy Tee",value:"₹13,500",signal:"Size selected · checkout started"},{customer:"M••• P••••",bag:"Bone Utility Overshirt",value:"₹11,400",signal:"Delivery page reached"},{customer:"R•••• S••••",bag:"Shadow Cargo 02",value:"₹9,800",signal:"Saved after payment failure"}].map((item) => <article key={item.customer}><ShoppingBag size={19} /><div><span>{item.customer}</span><h2>{item.bag}</h2><p>{item.signal}</p></div><strong>{item.value}</strong><button type="button">Inspect eligibility</button></article>)}</div></section>;

  const strategies = ["Complete the uniform", "Similar construction", "Recently viewed", "Collection affinity"];
  return <section className="admin-workspace"><div className="admin-heading"><p>Marketing / Recommendation controls</p><h1>Guide discovery.</h1><span>Explicit strategies, safe fallbacks, inventory awareness, and measurable placement—not opaque browser ranking.</span></div><div className="recommendation-lab"><aside><p>Placement strategy</p>{strategies.map((item) => <button className={strategy === item ? "is-active" : ""} onClick={() => setStrategy(item)} type="button" key={item}><Sparkles size={15} />{item}</button>)}</aside><main><header><div><Eye size={18} /><p><span>Preview / Product detail</span><strong>{strategy}</strong></p></div><span>Inventory-aware</span></header><div className="recommendation-preview">{[{name:"Core Heavy Tee",meta:"Ink · 240 GSM",icon:Heart},{name:"Shadow Cargo 02",meta:"Washed black · Utility",icon:Gift},{name:"Nocturne Cap",meta:"One size · Limited",icon:Users}].map(({name,meta,icon:Icon}, index) => <article key={name}><div><Icon size={23} /><span>0{index + 1}</span></div><h2>{name}</h2><p>{meta}</p><small>{index === 2 ? "Fallback item" : "Strategy match"}</small></article>)}</div><footer><Clock3 size={15} /> Preview uses fixture signals. Production ranking and measurement remain API-authoritative.</footer></main></div></section>;
}
