import { Check, Clock3, EyeOff, FileClock, KeyRound, LockKeyhole, Search, ShieldCheck, UserCog, Users } from "lucide-react";

export type AccessOperationsView = "roles" | "permissions" | "audit-log";

const roles = [
  { name: "ADMIN", people: 2, scope: "All stores and financial domains", grants: "All explicit permissions", tone: "Critical" },
  { name: "MANAGER", people: 5, scope: "Assigned stores", grants: "Catalog, orders, returns, CMS, reports", tone: "Operational" },
  { name: "WAREHOUSE", people: 14, scope: "Assigned warehouses and waves", grants: "Pick, pack, dispatch, inventory, QC", tone: "Task" },
  { name: "SUPPORT", people: 8, scope: "Assigned ticket queues", grants: "Masked context, tickets, refund request", tone: "Restricted" },
];

export function AccessOperations({ view }: { view: AccessOperationsView }) {
  if (view === "roles") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Access / Role bundles</p><h1>Bundle, never assume.</h1><span>Roles collect explicit permissions; store, warehouse, row, field, and action scopes remain independently enforced.</span></div><button className="admin-primary" type="button"><UserCog size={15} /> Create custom role</button></div><div className="role-cards">{roles.map((role) => <article key={role.name}><header><span><Users size={18} /> {role.people.toString().padStart(2,"0")} people</span><b>{role.tone}</b></header><h2>{role.name}</h2><p>{role.scope}</p><div><KeyRound size={15} /><span>{role.grants}</span></div><button type="button">Review bundle</button></article>)}</div><div className="admin-action-bar"><p><ShieldCheck size={14} /> A person cannot grant a permission or resource scope they do not hold.</p><button type="button">Compare roles</button></div></section>;

  if (view === "permissions") return <section className="admin-workspace"><div className="admin-heading"><p>Access / Permission registry</p><h1>Deny by default.</h1><span>Every protected route and mutation names an exact grant, visible scopes, masking rule, and audit posture.</span></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label="Search permissions" placeholder="Permission, route, domain" /></label><button type="button">Domain · All</button></div><div className="permission-matrix"><header><span>Permission</span><span>Manager</span><span>Warehouse</span><span>Support</span><span>Audit</span></header>{[{permission:"orders.view",values:[true,true,true],audit:"Read log"},{permission:"refunds.approve",values:[true,false,false],audit:"Reason + before/after"},{permission:"inventory.adjust",values:[true,false,false],audit:"Reason + movement"},{permission:"support.tickets.manage",values:[false,false,true],audit:"Thread event"},{permission:"staff.manage",values:[false,false,false],audit:"Admin only"},{permission:"customers.view_pii",values:[false,false,false],audit:"Reason + field log"}].map((row) => <article key={row.permission}><code>{row.permission}</code>{row.values.map((value,index) => <span key={index}>{value ? <Check size={15} /> : <LockKeyhole size={14} />}</span>)}<small>{row.audit}</small></article>)}</div><div className="admin-alert"><EyeOff size={20} /><div><strong>Masked data stays masked</strong><p>A route grant never implies permission to unmask a protected field.</p></div></div></section>;

  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Access / Immutable audit</p><h1>Who changed what.</h1><span>Actor, permission, request, reason, resource, before/after state, and exact time—append-only and export-controlled.</span></div><button className="admin-primary" type="button"><FileClock size={15} /> Export permitted log</button></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label="Search audit log" placeholder="Actor, action, resource, request" /></label><button type="button">Risk · All</button><button type="button">Last 24 hours</button></div><div className="audit-stream">{[{time:"14:42:18",actor:"Aarav D.",action:"refund.requested",resource:"ref_ICE072 · IO-2026-1027",permission:"refunds.request",reason:"Approved return passed QC"},{time:"14:36:04",actor:"Mira P.",action:"inventory.adjusted",resource:"ADH-BLK-L · BLR-01",permission:"inventory.adjust",reason:"Cycle count variance +1"},{time:"14:28:51",actor:"System",action:"payment.reconciled",resource:"pay_ICE1048 · set_ICE084",permission:"service.payment",reason:"Exact provider line match"},{time:"14:18:09",actor:"Neha A.",action:"customer.pii_viewed",resource:"cus-2047 · email",permission:"customers.view_pii",reason:"Assigned payment support case"}].map((event,index) => <article key={event.time}><div><Clock3 size={15} /><span>{event.time}<small>04 Aug 2026 · IST</small></span></div><i /><div><strong>{event.action}</strong><span>{event.resource}</span><p>{event.reason}</p></div><code>{event.permission}</code><span>{event.actor}</span><b>REQ-{8842-index}</b></article>)}</div></section>;
}
