import { Check, CreditCard, Globe2, KeyRound, Landmark, Link2, MapPinned, ReceiptText, Save, ShieldCheck, Truck } from "lucide-react";

export type SettingsOperationsView = "tax" | "localization" | "payments" | "shipping" | "integrations" | "security";

const settingsCopy: Record<SettingsOperationsView, { title: string; copy: string }> = {
  tax: { title:"Tax configuration", copy:"Registered origin, inclusive pricing, category treatment, invoice sequence, and effective-dated rules." },
  localization: { title:"Localization", copy:"Store locale, currency formatting, time zone, address shapes, and translation fallback without route drift." },
  payments: { title:"Payment providers", copy:"Provider health, permitted methods, capture posture, webhook state, reconciliation, and secret rotation boundaries." },
  shipping: { title:"Shipping configuration", copy:"Serviceability, courier services, promises, cutoffs, package rules, NDR, and RTO controls." },
  integrations: { title:"Integration registry", copy:"Owned connections, scoped credentials, last synchronization, webhook health, and revocation." },
  security: { title:"Security policy", copy:"Staff MFA, session lifetime, re-authentication, export controls, upload rules, and emergency revocation." },
};

export function SettingsOperations({ view }: { view: SettingsOperationsView }) {
  const page = settingsCopy[view];
  if (view === "payments") return <section className="admin-workspace"><SettingsHeading view={view} {...page} /><div className="provider-settings">{[{name:"Razorpay",type:"Cards · UPI · Netbanking",health:"Healthy",mode:"Primary"},{name:"Cashfree",type:"UPI fallback",health:"Healthy",mode:"Fallback"},{name:"COD settlement",type:"Courier remittance",health:"Attention",mode:"Enabled"}].map((provider) => <article key={provider.name}><CreditCard size={22} /><div><span>{provider.mode}</span><h2>{provider.name}</h2><p>{provider.type}</p></div><span className={`admin-status ${provider.health === "Healthy" ? "admin-status--captured" : "admin-status--review"}`}>{provider.health}</span><button type="button">Configure</button></article>)}</div><SafetyCallout /></section>;
  if (view === "shipping") return <section className="admin-workspace"><SettingsHeading view={view} {...page} /><div className="shipping-settings"><article><Truck size={23} /><h2>Standard delivery</h2><p>India · 3–6 business days</p><label>Free above<input defaultValue="₹7,500" /></label><label>Base rate<input defaultValue="₹250" /></label><span><Check size={13} /> Active · Blue Dart, Delhivery</span></article><article><MapPinned size={23} /><h2>Express delivery</h2><p>Selected pincodes · 1–3 business days</p><label>Minimum order<input defaultValue="₹3,000" /></label><label>Base rate<input defaultValue="₹450" /></label><span><Check size={13} /> Serviceability required</span></article><aside><ReceiptText size={22} /><h2>Promise rules</h2><p>Estimates are returned by the shipping API after address, cart, cutoff, warehouse, and provider checks.</p><button type="button">Open package profiles</button></aside></div><SafetyCallout /></section>;
  if (view === "integrations") return <section className="admin-workspace"><SettingsHeading view={view} {...page} /><div className="integration-grid">{[{name:"Razorpay",owner:"Payments",sync:"Webhook · 1 min ago",state:"Healthy"},{name:"Blue Dart",owner:"Shipping",sync:"Polling · 4 min ago",state:"Healthy"},{name:"Delhivery",owner:"Shipping",sync:"Webhook · 8 min ago",state:"Attention"},{name:"Email provider",owner:"Notifications",sync:"API · now",state:"Healthy"}].map((item) => <article key={item.name}><Link2 size={21} /><div><span>{item.owner}</span><h2>{item.name}</h2><p>{item.sync}</p></div><span className={`admin-status ${item.state === "Healthy" ? "admin-status--captured" : "admin-status--review"}`}>{item.state}</span><button type="button">Inspect</button></article>)}</div><SafetyCallout /></section>;
  if (view === "security") return <section className="admin-workspace"><SettingsHeading view={view} {...page} /><div className="security-policy"><article><ShieldCheck size={22} /><div><span>Staff MFA</span><strong>Required for all roles</strong><small>Recovery codes audited</small></div><input aria-label="Require staff MFA" type="checkbox" defaultChecked /></article><article><KeyRound size={22} /><div><span>Re-authentication</span><strong>Dangerous actions · 10 min</strong><small>Settings, refunds, exports, PII</small></div><input aria-label="Require re-authentication" type="checkbox" defaultChecked /></article><article><Globe2 size={22} /><div><span>Session lifetime</span><strong>8 hours · idle 30 min</strong><small>Audience-separated refresh sessions</small></div><button type="button">Edit policy</button></article><article><Landmark size={22} /><div><span>Financial exports</span><strong>Reason + narrow permission</strong><small>Watermarked and audit logged</small></div><input aria-label="Protect financial exports" type="checkbox" defaultChecked /></article></div><SafetyCallout /></section>;

  return <section className="admin-workspace"><SettingsHeading view={view} {...page} /><div className="settings-form-grid">{view === "tax" ? <><label>Registered country<select defaultValue="India"><option>India</option></select></label><label>Pricing display<select defaultValue="Tax inclusive"><option>Tax inclusive</option></select></label><label>GST registration<input defaultValue="29ABCDE1234F1Z5" /></label><label>Invoice prefix<input defaultValue="IO-INV-2026" /></label><label>Standard apparel rate<input defaultValue="12%" /></label><label>Rule effective from<input type="date" defaultValue="2026-08-01" /></label></> :<><label>Default locale<select defaultValue="en-IN"><option>en-IN</option></select></label><label>Default currency<select defaultValue="INR"><option>INR</option></select></label><label>Time zone<select defaultValue="Asia/Kolkata"><option>Asia/Kolkata</option></select></label><label>Number format<input defaultValue="12,34,567.89" /></label><label>Date format<input defaultValue="DD MMM YYYY" /></label><label>Fallback locale<input defaultValue="en-IN" /></label></>}</div><SafetyCallout /></section>;
}

function SettingsHeading({ view, title, copy }: { view: SettingsOperationsView; title: string; copy: string }) { return <div className="admin-heading admin-heading--actions"><div><p>Settings / {view}</p><h1>{title}.</h1><span>{copy}</span></div><button className="admin-primary" type="button"><Save size={15} /> Save preview</button></div>; }
function SafetyCallout() { return <div className="settings-callout"><ShieldCheck size={16} /><p><strong>Production changes require re-authentication and an audit reason.</strong><span>This frontend preview does not change providers, policy, secrets, tax, or serviceability.</span></p></div>; }
