"use client";

import { BookOpenText, Check, Clock3, Eye, MessageCircle, MessageSquareText, Plus, Search, Send, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";

export type AdminSupportView = "faq" | "chat";

const faqRows = [
  { question: "How does the fit run?", category: "Product and fit", locale: "en-IN", state: "Published", views: "2,840" },
  { question: "When can I request a return?", category: "Returns", locale: "en-IN", state: "Published", views: "1,926" },
  { question: "Where is my refund?", category: "Payments", locale: "en-IN", state: "Review", views: "1,102" },
];

export function AdminSupportPages({ view }: { view: AdminSupportView }) {
  const [selected, setSelected] = useState(0);
  if (view === "faq") return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Support / Knowledge base</p><h1>Answer before the queue.</h1><span>Versioned, searchable, locale-aware answers with product, policy, and escalation links that stay valid.</span></div><button className="admin-primary" type="button"><Plus size={15} /> New answer</button></div><div className="faq-health"><article><BookOpenText size={20} /><span>Published answers</span><strong>42</strong><small>5 categories · en-IN</small></article><article><Search size={20} /><span>Self-service rate</span><strong>64%</strong><small>7-day successful exits</small></article><article><MessageSquareText size={20} /><span>Still created tickets</span><strong>18%</strong><small>Delivery leads the gap</small></article></div><div className="admin-toolbar"><label><Search size={16} /><input aria-label="Search FAQ entries" placeholder="Question, keyword, policy" /></label><button type="button">Category · All</button><button type="button">Locale · en-IN</button></div><div className="faq-records">{faqRows.map((item) => <article key={item.question}><BookOpenText size={18} /><div><span>{item.category} · {item.locale}</span><h2>{item.question}</h2><p>{item.views} helpful views this month</p></div><span className={`admin-status ${item.state === "Published" ? "admin-status--captured" : "admin-status--review"}`}>{item.state}</span><button type="button"><Eye size={15} /> Edit answer</button></article>)}</div></section>;

  const chats = [
    { customer: "A•••• K••••", topic: "Fit before checkout", wait: "Now", state: "Active" },
    { customer: "M••• P••••", topic: "Courier attempt", wait: "2 min", state: "Queued" },
    { customer: "R•••• S••••", topic: "Refund timeline", wait: "5 min", state: "Queued" },
  ];
  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Support / Live chat</p><h1>Resolve in the moment.</h1><span>Consent-aware live conversation with masked customer and commerce context, queue state, and transcript handoff.</span></div><span className="warehouse-shift"><i className="status-dot" /> 03 agents online</span></div><div className="live-chat-console"><aside><header><strong>Conversation queue</strong><span>03</span></header>{chats.map((chat, index) => <button className={selected === index ? "is-active" : ""} onClick={() => setSelected(index)} type="button" key={chat.customer}><UserRound size={17} /><span><strong>{chat.customer}</strong><small>{chat.topic}</small></span><b>{chat.wait}</b></button>)}</aside><main><header><div><MessageCircle size={18} /><p><strong>{chats[selected].customer}</strong><small>{chats[selected].topic} · secure web chat</small></p></div><span className="admin-status admin-status--captured">{chats[selected].state}</span></header><div className="support-messages"><article className="is-system"><ShieldCheck size={15} /><p>Identity and consent state verified. Only masked account context is attached.</p></article><article className="is-customer"><span>Customer · 14:41</span><p>I am between sizes on the overshirt. Can you help me compare the actual garment measurements?</p></article><article className="is-agent"><span>Aarav D. · 14:42</span><p>Yes. I can compare the chest and shoulder measurements with the size you already own—no personal details needed.</p></article></div><form className="support-reply"><textarea aria-label="Reply to live chat" placeholder="Reply with approved context…" rows={3} /><div><span>Fit guide · Product link · Internal note</span><button type="button"><Send size={14} /> Send preview</button></div></form></main><aside className="chat-context"><p>Session context</p><div><Clock3 size={16} /><span>Queue SLA<strong>7 minutes left</strong></span></div><div><Eye size={16} /><span>Current page<strong>/product/bone-utility-overshirt</strong></span></div><div><Check size={16} /><span>Customer state<strong>Verified · no open order</strong></span></div><button type="button">Convert to ticket</button></aside></div></section>;
}

export function AdminTicketDetail({ ticketId }: { ticketId: string }) {
  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Support / Ticket detail</p><h1>{ticketId}</h1><span>Append-only thread, SLA state, ownership, linked commerce context, and escalation evidence.</span></div><span className="admin-status admin-status--review">Priority · 18 min</span></div><div className="ticket-detail-grid"><main><header><div><span>Payment captured, order pending</span><h2>Customer needs confirmation before the drop closes.</h2></div><button type="button">Reassign</button></header><div className="support-messages"><article className="is-customer"><span>R•••• S•••• · 14:18</span><p>The payment completed but the order is still waiting. I do not want to pay twice.</p></article><article className="is-system"><ShieldCheck size={15} /><p>Provider capture is verified. Order confirmation event is delayed; duplicate checkout should be discouraged.</p></article><article className="is-agent"><span>Aarav D. · 14:24</span><p>Your payment is safe. I have linked the verified reference to our order queue and will update this thread.</p></article></div><form className="support-reply"><textarea aria-label="Reply to support ticket" rows={4} placeholder="Reply or add an internal note…" /><div><span>Public reply · Approved macros</span><button type="button"><Send size={14} /> Send preview</button></div></form></main><aside><p className="eyebrow">Resolution controls</p><dl><div><dt>Assignee</dt><dd>Aarav D.</dd></div><div><dt>Queue</dt><dd>Payment priority</dd></div><div><dt>Waiting state</dt><dd>Internal team</dd></div><div><dt>Linked order</dt><dd>IO-2026-1047</dd></div><div><dt>Payment</dt><dd>₹8,900 · Captured</dd></div></dl><button type="button">Escalate with transcript</button><button type="button">Pause SLA · customer</button><button type="button" disabled>Close after resolution</button></aside></div></section>;
}
