"use client";

import { Clock3, CreditCard, MessageSquareText, Package, Send, ShieldCheck, Truck, UserRound } from "lucide-react";
import { useState } from "react";

const tickets = [
  { id: "TKT-2041", title: "Payment captured, order pending", customer: "Riya S.", sla: "18 min", state: "Priority" },
  { id: "TKT-2039", title: "Exchange size availability", customer: "Aarav K.", sla: "Paused", state: "Waiting" },
  { id: "TKT-2032", title: "Courier marked unavailable", customer: "Maya P.", sla: "44 min", state: "Open" },
];

export function AdminSupportWorkspace() {
  const [selected, setSelected] = useState(tickets[0]);
  return <section className="admin-support-page"><header><div><p>Support / Assigned queue</p><h1>Keep the context.</h1><span>Thread, SLA, order, payment, shipment, and return facts stay beside each other.</span></div><div><span><i className="status-dot" /> 03 online</span><button type="button">Take next ticket</button></div></header><div className="support-console"><aside className="support-ticket-list"><div><strong>My queue</strong><span>03 open</span></div>{tickets.map((ticket) => <button className={selected.id === ticket.id ? "is-active" : ""} onClick={() => setSelected(ticket)} type="button" key={ticket.id}><span>{ticket.id} · {ticket.sla}</span><strong>{ticket.title}</strong><small>{ticket.customer} · {ticket.state}</small></button>)}</aside><main className="support-thread"><header><div><span>{selected.id}</span><h2>{selected.title}</h2><p>{selected.customer} · Waiting 12 min</p></div><span className="admin-status admin-status--review">{selected.state}</span></header><div className="support-messages"><article className="is-customer"><span>Customer · 14:18</span><p>I completed the UPI payment, but my account still shows that the order is waiting for confirmation.</p></article><article className="is-system"><ShieldCheck size={15} /><p>Masked payment context attached. Capture is verified; order confirmation remains blocked by a delayed event.</p></article><article className="is-agent"><span>Aarav D. · 14:24</span><p>I can see the verified capture. I’m linking the payment evidence to the order team now—please do not place a second order.</p></article></div><form className="support-reply"><textarea aria-label="Reply to ticket" placeholder="Reply with approved, contextual information…" rows={3} /><div><span>Macros · Attach context · Internal note</span><button type="button"><Send size={14} /> Send preview</button></div></form></main><aside className="support-context"><p>Permission-masked context</p><article><UserRound size={16} /><div><span>Customer</span><strong>R•••• S••••</strong><small>ri•••@example.com</small></div></article><article><Package size={16} /><div><span>Order</span><strong>IO-2026-1047</strong><small>1 piece · confirmation blocked</small></div></article><article><CreditCard size={16} /><div><span>Payment</span><strong>₹8,900 · Captured</strong><small>pay_••••1047</small></div></article><article><Truck size={16} /><div><span>Shipment</span><strong>Not allocated</strong><small>No AWB exists</small></div></article><article><Clock3 size={16} /><div><span>SLA</span><strong>18 minutes left</strong><small>Priority payment queue</small></div></article><button type="button"><MessageSquareText size={15} /> Escalate with transcript</button></aside></div></section>;
}
