"use client";

import { Check, Flag, Image as ImageIcon, MessageSquareReply, ShieldAlert, Star, X } from "lucide-react";
import { useState } from "react";

export function AdminReviewModeration() {
  const [decision, setDecision] = useState("Pending");
  return <section className="admin-workspace"><div className="admin-heading admin-heading--actions"><div><p>Reviews / Moderation</p><h1>Moderate policy.<br />Not sentiment.</h1><span>Verified purchase context, media safety, policy evidence, and merchant reply in one review desk.</span></div><span className="admin-status admin-status--review">08 awaiting review</span></div><div className="review-moderation-layout"><aside><div><span>Queue</span><strong>08 pending</strong></div>{["Afterdark Hoodie", "Bone Utility Overshirt", "Core Heavy Tee"].map((name, index) => <button className={index === 0 ? "is-active" : ""} type="button" key={name}><span>REV-20{41 - index}</span><strong>{name}</strong><small>{index === 0 ? "5 stars · 2 images" : `${4 - index} stars · no media`}</small></button>)}</aside><main><header><div className="review-rating"><strong>5.0</strong><span>{Array.from({length:5}, (_, index) => <Star fill="currentColor" size={15} key={index} />)}</span><small>Verified purchase · IO-2026-1027</small></div><span className={`admin-status ${decision === "Approved" ? "admin-status--captured" : decision === "Rejected" ? "admin-status--failed" : "admin-status--review"}`}>{decision}</span></header><article><p className="eyebrow">True to size / Bone / L</p><h2>Built like an outer layer should be.</h2><blockquote>The canvas has real structure without fighting movement. The shoulders sit exactly where the size guide suggested.</blockquote><span>Customer identity masked · submitted 04 Aug</span></article><div className="review-media"><div><ImageIcon size={22} /><span>Customer image 01</span></div><div><ImageIcon size={22} /><span>Customer image 02</span></div></div><div className="review-policy"><ShieldAlert size={17} /><p><strong>Automated safety checks passed</strong><span>No detected PII, prohibited content, or unverified commercial claim.</span></p></div><div className="review-decisions"><button onClick={() => setDecision("Approved")} type="button"><Check size={15} /> Approve</button><button onClick={() => setDecision("Rejected")} type="button"><X size={15} /> Reject with reason</button><button type="button"><Flag size={15} /> Escalate</button><button type="button"><MessageSquareReply size={15} /> Draft merchant reply</button></div></main></div></section>;
}
